// The affirmations pool: whole phrases, shown one at a time in place of the
// single words when the text mode (Text, in the words section) is set to
// affirmations. No themes; the set is its own theme. Kept apart from
// words.js so the set can grow without touching the word table.
//
// Smart breaks: a | marks where a phrase breaks into its own lines when
// Smart breaks is on (Text, under Line width), each line one complete idea.
// A phrase with none just wraps to the line width. The markers never show:
// AFFIRMATIONS below is the clean text, and SMART_BREAKS maps each marked
// phrase to its lines.
const RAW = [
  'Trusting that you are supported.',
  'Everything that you need is flowing toward you now.',
  'The universe has a beautiful plan for you.',
  'You are loved.',
  'You are worthy.',
  'You deserve good things in life.',
  'Peace is right here.|With this breath.',
  'Breathing in this moment.',
  'You are more supported than you know.',
  'Here.|In this moment.|Everything is ok.',
  'Staying with the breath.',
  'Noticing the rise and fall of the breath.',
  'Feeling gratitude for giving yourself this moment.',
  'Feeling gratitude for all your friends and loved ones.',
  'This life adventure has only just begun.',
  'There’s so much joy in store for you.',
  'The gifts are already on their way.',
  'There’s so much happiness in store for you.',
  'Nothing needs to change for peace to be here.',
  'You are only just beginning to tap into your gifts.',
  'A beam inside you draws strength from an unending source.',
  'Your healing is the healing of the collective.',
  'A more beautiful world is possible.',
  'Your heart is so worthy of nourishment and care.',
  'Your needs matter.',
  'Caring for yourself in beautiful ways.',
  'You are learning to fully show up for yourself.',
  'Everything that’s arising here is ok.',
  'It’s ok to feel whatever you are feeling.',
  'From where do these sensations arise?',
  'To whom do these sensations belong?',
  'Can you be just a little softer toward yourself?',
  'Can you find a way to be 1% more comfortable?',
  'Are you open to receiving love?',
  'What if abundance were already on its way?',
  'Your creative spirit is extraordinary.',
  'You have so many gifts to share with the world.',
  'This moment.|Here and now.|Is enough.',
  'You are so deeply loved.',
  'The universe is on your side.',
  'Your ancestors are looking out for you.',
  'Every day, you are becoming more integrated and whole.',
  'This is a journey of wonder and magic.',
  'What lies ahead is beyond your wildest imagination.',
  'How good can it get?',
  'Your parts are so grateful for your loving presence.',
  'Noticing the sensations in your body.',
  'Any thoughts that arise are ok to be here.',
  'How would it feel to trust that nothing is wrong?',
  'What if everything were unfolding perfectly?',
  'Do you notice any warmth in your body?',
  'Do you notice any good feelings in your body?',
  // round one of sandbox/affirmation-sort.html, the yeses with their edits
  'You are enough.',
  'You belong.',
  'You are whole.',
  'Nothing to prove.',
  'You are a gift.',
  'You can rest now.',
  'You can let go.',
  'Rest is allowed.',
  'There’s no hurry.',
  'Nothing to fix.',
  'Nothing to do.',
  'Nothing to get.',
  'It can be easy.',
  'Softening.',
  'Just this breath.',
  'Right here.',
  'Only this moment.',
  'This is enough.',
  'Nowhere else to be.',
  'You are safe.',
  'You are held.',
  'All is well.',
  'It’s ok.',
  'Life is on your side.',
  'You are not alone.',
  'The ground holds you.',
  'You are cherished.',
  'You are so loved.',
  'Being gentle with yourself.',
  'Feeling your feet.',
  'Feeling the ground.',
  'Your body knows.',
  'Your body is wise.',
  'Relaxing your jaw.',
  'You are healing.',
  'One breath at a time.',
  'You are learning.',
  'A little lighter each day.',
  'You are finding your way.',
  'It’s all unfolding.',
  'Trusting the timing.',
  'Thank you.',
  'So much to be grateful for.',
  'This is a gift.',
  'Grateful for this breath.',
  'What if it’s all ok?',
  'What if you’re already enough?',
  'Can you rest here?',
  'Can you soften, just a little?',
  'What feels good right now?',
  'What if nothing is wrong?',
  'Here.|Now.|Safe.',
  'Soft.|Open.|Free.',
  'You are here.|You are safe.',
  'Slowing down.|You’re ok.',
  'Letting go.|You’re held.',
  'Being still.|Being here.',
  'Nothing to prove.|Nothing to fix.',
  'You are free.',
  // round two, the yeses
  'You are welcome.',
  'Breathing.',
  'Resting.',
  'Settling.',
  'Letting go.',
  'Listening.',
  'Noticing.',
  'Allowing.',
  'Opening.',
  'Slowing down.',
  'Sinking in.',
  'Unwinding.',
  'Returning to the breath.',
  'Coming home to yourself.',
  'Nothing to carry.',
  'Nothing to solve.',
  'Nothing to change.',
  'Nothing to become.',
  'Nothing to hold.',
  'Nowhere to go.',
  'No one to be.',
  'Nothing is required.',
  'Nothing is missing.',
  'Just this.',
  'Just this moment.',
  'This breath is enough.',
  'This moment is enough.',
  'Stillness is here.',
  'You are supported.',
  'It’s safe to soften.',
  'Rest is healing.',
  'Rest is enough.',
  'You deserve rest.',
  'Taking your time.',
  'No rush.',
  'Easy now.',
  'Feeling your breath.',
  'Feeling your hands.',
  'Feeling your weight.',
  'Letting the ground take your weight.',
  'Your breath knows the way.',
  'Your body is safe.',
  'Your heart knows.',
  'Unclenching.',
  'Soft face.',
  'Softening your eyes.',
  'Letting your breath be easy.',
  'You are softening.',
  'You are remembering.',
  'You are doing enough.',
  'Gently, gently.',
  'Grateful for this moment.',
  'Grateful for this body.',
  'Thank you, breath.',
  'Thank you, body.',
  'This breath is a gift.',
  'Can you feel your breath?',
  'Can you feel the ground?',
  'What wants to soften?',
  'What if you are already home?',
  'Can you let go, just a little?',
  'Breathing in.|Breathing out.',
  'Softening.|Settling.|Resting.',
  'Still.|Safe.|Here.',
  'Letting go.|Letting be.',
  'Here.|Now.|Held.',
  'You are held.|You are home.',
  'Nothing to do.|Just being.',
  // round three, the yeses, commands turned to -ing so each lands as
  // something already happening
  'Releasing.',
  'Receiving.',
  'Relaxing.',
  'Trusting.',
  'Welcoming.',
  'Drifting.',
  'Floating.',
  'Coming back.',
  'Letting it be.',
  'Letting yourself rest.',
  'Resting in the breath.',
  'Being breathed.',
  'Nothing to chase.',
  'Nothing to fight.',
  'Nothing to know.',
  'Nothing to earn.',
  'Nothing to manage.',
  'Nothing to figure out.',
  'No one to please.',
  'Nothing needs to happen.',
  'Just breathing.',
  'Just resting.',
  'Just noticing.',
  'Just here.',
  'Feeling your belly rise.',
  'Feeling your chest soften.',
  'Feeling your heartbeat.',
  'Feeling the air on your skin.',
  'Feeling your back.',
  'Softening your hands.',
  'Softening your brow.',
  'Softening your belly.',
  'Softening your tongue.',
  'Loosening your shoulders.',
  'Unclenching your hands.',
  'Your hands can rest.',
  'Letting your belly be soft.',
  'Can you feel your hands?',
  'Can you feel your feet?',
  'Can you feel your heartbeat?',
  'Can you feel the stillness?',
  'Can you soften your jaw?',
  'What wants to let go?',
  'What is here now?',
  'Where is the breath?',
  'What does your body need?',
  'What if you are already held?',
  'You are home.',
  'You are allowed.',
  'Listening to your body.',
  'At home in your body.',
  'Thank you, heart.',
  'Thank you, earth.',
  'Thank you, hands.',
  'Grateful for this stillness.',
  'Grateful to be here.',
  'This moment is a gift.',
  'Trusting the breath.',
  'Everything is allowed.',
  'Breathing.|Softening.|Resting.',
  'Soft.|Still.|Safe.',
  'Here.|Now.|Home.',
  'Letting go.|Letting in.',
  'Nothing to do.|Nowhere to go.',
  'You are safe.|You are free.',
  'Slow.|Soft.|Still.',
  'Just this.|Just now.',
  'Feeling.|Softening.|Releasing.',
  'Breathing in.|Softening.',
  'Resting.|Receiving.|Returning.',
  'Breathing in.|Letting go.'
];

const pieces = RAW.map(r => r.split('|').map(t => t.trim()).filter(Boolean));
export const AFFIRMATIONS = pieces.map(p => p.join(' '));
export const SMART_BREAKS = new Map(pieces.filter(p => p.length > 1).map(p => [p.join(' '), p]));
