// The Web Audio graph: a modulated tone, a pip train, a panned harmonic stack,
// and two reverb sends. Everything sounding is generated by one AudioWorklet
// from a single sample-accurate phase accumulator (see worklet.js).
import { S } from './state.js';
import { $ } from './dom.js';

let audioCtx = null, volGain = null, node = null;
let harmDry = null, harmWet = null, convolver = null, clickWet = null;
let clickConv = null, irTimer = null;
let graphPromise = null, deviceWarm = false, audioHasPlayed = false;

// The worklet used to be a template literal turned into a Blob URL. As a real
// file it can be handed straight to addModule(). The URL is resolved against
// this module rather than the document so it keeps working from a subpath.
const WORKLET_URL = new URL('./worklet.js', import.meta.url).href;
window.__WORKLET_URL = WORKLET_URL;   // exposed so tests can render it offline

export const isDeviceWarm = () => deviceWarm;
export const hasNode = () => !!node;
export const getContext = () => audioCtx;

// A decaying noise burst is a perfectly serviceable reverb impulse, and it
// costs nothing to generate compared with shipping an audio file.
function makeImpulse(seconds, decay) {
  const sr = audioCtx.sampleRate, len = Math.floor(sr * seconds);
  const buf = audioCtx.createBuffer(2, len, sr);
  for (let ch = 0; ch < 2; ch++) {
    const d = buf.getChannelData(ch);
    for (let i = 0; i < len; i++) {
      d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, decay);
    }
  }
  return buf;
}

// Rebuilding an impulse means filling up to 8 seconds of stereo noise, so the
// slider is debounced. Swapping the buffer mid-tail truncates whatever is
// still ringing, which is unavoidable and brief.
export function rebuildClickIR() {
  if (!clickConv) return;
  clearTimeout(irTimer);
  irTimer = setTimeout(() => {
    if (clickConv) clickConv.buffer = makeImpulse(S.clickRevTime, 2.5);
  }, 140);
}

export function applyReverbMix() {
  if (!harmDry) return;
  const t = audioCtx.currentTime;
  // equal-power crossfade so the total stays level as reverb comes up
  harmDry.gain.setTargetAtTime(Math.cos(S.harmReverb * Math.PI / 2), t, 0.05);
  harmWet.gain.setTargetAtTime(Math.sin(S.harmReverb * Math.PI / 2) * 0.9, t, 0.05);
  if (clickWet) clickWet.gain.setTargetAtTime(S.clickReverb * 0.9, t, 0.05);
}

// Deliberately does not touch harmLevel. That param is owned by rampLevel,
// and driving one AudioParam with both setTargetAtTime and a cancelled linear
// ramp is what was producing the click.
export function applyHarmonics() {
  setParam('harmCount',  S.harmCount,   0.001);
  setParam('harmBright', 3.2 - S.harmBright * 3.0, 0.02);   // slider is brightness; the worklet wants rolloff
  setParam('harmSpread', S.harmSpread,  0.05);
  setParam('harmPanRate',S.harmPanRate, 0.05);
  setParam('clickModDepth', S.clickModDepth, 0.05);
  setParam('clickModRate',  1 / S.clickModPeriod, 0.05);   // control is seconds per cycle
  setParam('biDepth', S.biDepth, 0.05);
  setParam('biRate',  1 / S.biPeriod, 0.05);               // one full left-right pass
  setParam('biHard',  S.biHardSwitch ? 1 : 0, 0.001);
  setParam('shimDepth',  S.shimDepth,   0.05);
  setParam('shimRate',   S.shimRate,    0.05);
}

// A ramp with no preceding automation event has no defined start value and can
// jump straight to the target, which is the click you hear on the first play.
// Anchoring the current value first makes every ramp actually ramp. Mixing
// linearRamp and setTarget on one param does the same thing, so master volume
// uses only this path.
function rampVol(target, dur, startAt) {
  if (!volGain) return;
  const g = volGain.gain;
  const now = audioCtx.currentTime;
  const t = startAt !== undefined ? startAt : now;
  g.cancelScheduledValues(now);
  g.setValueAtTime(g.value, now);
  if (t > now) g.setValueAtTime(g.value, t);
  g.linearRampToValueAtTime(target, t + dur);
}

export function setParam(name, value, glide = 0.02) {
  if (!node) return;
  const prm = node.parameters.get(name);
  if (!prm) return;
  // out-of-range values get silently clamped by the engine, which hides real
  // bugs. Clamp here so the value sent is always the value meant.
  const v = Math.min(prm.maxValue, Math.max(prm.minValue, value));
  prm.setTargetAtTime(v, audioCtx.currentTime, glide);
}

// Levels get an explicit linear ramp rather than an exponential approach, so
// they start at exactly zero and arrive at exactly the target.
function rampLevel(name, target, dur = 0.25, lead = 0) {
  if (!node) return;
  const prm = node.parameters.get(name);
  if (!prm) return;
  const t = audioCtx.currentTime + lead;
  prm.cancelScheduledValues(t);
  prm.setValueAtTime(prm.value, t);
  prm.linearRampToValueAtTime(target, t + dur);
}

const levelTargets = {
  toneLevel:  () => S.audioEnabled && S.toneOn  ? S.toneVol  : 0,
  clickLevel: () => S.audioEnabled && S.clickOn ? S.clickVol : 0,
  harmLevel:  () => S.audioEnabled && S.harmOn  ? S.harmVol  : 0,
  clickSend:  () => S.audioEnabled && S.clickOn ? S.clickVol * S.clickReverb : 0
};

// Ramps one level only. Touching a slider used to re-ramp every level at once,
// which made the whole mix lurch whenever any one of them moved.
export function applyLevel(name, dur = 0.12, lead = 0) {
  rampLevel(name, levelTargets[name](), dur, lead);
}

export function applyAudioShape(lead = 0) {
  for (const name of Object.keys(levelTargets)) {
    rampLevel(name, levelTargets[name](), lead ? 0.3 : 0.12, lead);
  }
  applyHarmonics();
}

export function setAudioRate(hz) { setParam('rate', hz, 0.03); }
export const setAmRate = hz => setAudioRate(hz);

// The click on first play was never our gain ramp. Starting an AudioContext
// engages the output device, and Chrome compiling a worklet module the first
// time can underrun the audio thread: both happen before any automation of
// ours applies. So the graph is built once at the safety gate, minutes before
// anyone presses space, and then never torn down. Enabling audio afterwards
// is only a gain change on an already-warm device.
//
// Split deliberately. Building the graph needs no user gesture, so it happens
// at page load and the worklet is compiled long before anyone plays anything.
// Waking the output device does need a gesture, and that wake is what clicks,
// so it is triggered on the earliest gesture available rather than on play.
export function ensureAudioGraph() {
  if (graphPromise) return graphPromise;
  graphPromise = (async () => {
    const AC = window.AudioContext || window.webkitAudioContext;
    // 'interactive' is the default and gives the smallest possible buffer, which
    // underruns while the device spins up and clicks. Nothing here needs low
    // latency, so ask for the large buffer instead.
    audioCtx = new AC({ latencyHint: 'playback' });

    volGain = audioCtx.createGain();
    volGain.gain.value = 0;
    volGain.connect(audioCtx.destination);

    await audioCtx.audioWorklet.addModule(WORKLET_URL);

    node = new AudioWorkletNode(audioCtx, 'genus', {
      numberOfInputs: 0,
      numberOfOutputs: 3,
      outputChannelCount: [2, 2, 1]   // 0: tone and pips, 1: harmonics, 2: pip reverb send
    });
    node.connect(volGain, 0);

    // Harmonics get their own dry/wet pair so reverb applies to them alone.
    // The pulse itself must stay dry or the reverb tail fills in the gaps that
    // carry the entrainment.
    harmDry = audioCtx.createGain();
    harmWet = audioCtx.createGain();
    convolver = audioCtx.createConvolver();
    convolver.buffer = makeImpulse(2.6, 2.5);
    node.connect(harmDry, 1);
    node.connect(convolver, 1);
    convolver.connect(harmWet);
    harmDry.connect(volGain);
    harmWet.connect(volGain);

    // pips get their own send into the same room, so the dry pip stays sharp
    clickWet = audioCtx.createGain();
    clickConv = audioCtx.createConvolver();
    clickConv.buffer = makeImpulse(S.clickRevTime, 2.5);
    node.connect(clickConv, 2);
    clickConv.connect(clickWet);
    clickWet.connect(volGain);

    applyReverbMix();

    for (const nm of ['toneLevel','clickLevel']) {
      node.parameters.get(nm).setValueAtTime(0, audioCtx.currentTime);
    }
    setParam('rate',    S.amLinked ? S.effFreq : S.amRate, 0.001);
    setParam('carrier', S.carrierHz, 0.001);
    setParam('pipMs',   S.pipMs,     0.001);

    S.workletReady = true;
  })().catch(e => {
    console.warn('audio graph failed:', e);
    graphPromise = null;
  });
  return graphPromise;
}

// Wakes the output device. Everything is held at hard silence for a moment
// afterwards so the wake transient lands in silence rather than underneath
// whatever is about to fade in.
export async function warmDevice() {
  // nothing to wake for if audio is not in play
  if (!$('lAudio').checked && !S.audioEnabled) return;
  await ensureAudioGraph();
  if (!audioCtx || deviceWarm) return;
  deviceWarm = true;
  if (audioCtx.state === 'suspended') {
    try { await audioCtx.resume(); } catch (e) { deviceWarm = false; }
  }
}

export async function audioOn() {
  S.audioEnabled = true;
  await warmDevice();
  if (!S.workletReady) return;
  const firstStart = !audioHasPlayed;
  audioHasPlayed = true;
  const lead = firstStart ? 0.9 : 0;
  applyAudioShape(lead);
  rampVol(S.running ? S.volume : 0, firstStart ? 0.8 : 0.35, audioCtx.currentTime + lead);
}

// Deliberately keeps the context and the worklet alive. Closing and rebuilding
// them on every toggle reintroduces exactly the device-engagement click this
// is here to avoid.
export function audioOff() {
  S.audioEnabled = false;
  if (!audioCtx) return;
  applyAudioShape();
  rampVol(0, 0.25);
}

// spacebar pauses the whole experience, sound included
export function applyAudioGain() {
  if (!audioHasPlayed) return;    // first start is scheduled by audioOn, with its lead-in
  rampVol(S.running ? S.volume : 0, 0.12);
}
