// The Web Audio graph: a modulated tone, a pip train, a panned harmonic stack,
// and two reverb sends. Everything sounding is generated by one AudioWorklet
// from a single sample-accurate phase accumulator (see worklet.js).
import { S } from './state.js';
import { $ } from './dom.js';
import { buildChirp } from './chirp.js';

let audioCtx = null, volGain = null, node = null;
let harmDry = null, harmWet = null, convolver = null, clickWet = null;
let clickConv = null, irTimer = null;
let graphPromise = null, deviceWarm = false, audioHasPlayed = false;

// The worklet used to be a template literal turned into a Blob URL. As a real
// file it can be handed straight to addModule(). The URL is resolved against
// this module rather than the document so it keeps working from a subpath.
const WORKLET_URL = new URL('./worklet.js', import.meta.url).href;
window.__WORKLET_URL = WORKLET_URL;   // exposed so tests can render it offline

export const isDeviceWarm = () => deviceWarm;
export const hasNode = () => !!node;
export const getContext = () => audioCtx;
// The piano hangs off the same master gain the rest of the audio uses, so the
// volume slider and the transport mute reach it without any extra wiring.
export const getMaster = () => volGain;

// A decaying noise burst is a perfectly serviceable reverb impulse, and it
// costs nothing to generate compared with shipping an audio file.
function makeImpulse(seconds, decay) {
  const sr = audioCtx.sampleRate, len = Math.floor(sr * seconds);
  const buf = audioCtx.createBuffer(2, len, sr);
  for (let ch = 0; ch < 2; ch++) {
    const d = buf.getChannelData(ch);
    for (let i = 0; i < len; i++) {
      d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, decay);
    }
  }
  return buf;
}

// Rebuilding an impulse means filling up to 8 seconds of stereo noise, so the
// slider is debounced. Swapping the buffer mid-tail truncates whatever is
// still ringing, which is unavoidable and brief.
// The active pip shape owns its own level and room. Everything downstream reads
// through these three, so switching mode swaps the whole set at once and no
// chirp control can write into a click value or the reverse.
const trimGain = () => Math.pow(10, S.pipTrimDb / 20);
export const pipVol     = () => Math.min(1, (S.clickMode === 'chirp' ? S.chirpVol : S.clickVol) * trimGain());
export const pipReverb  = () => S.clickMode === 'chirp' ? S.chirpReverb  : S.clickReverb;
export const pipRevTime = () => S.clickMode === 'chirp' ? S.chirpRevTime : S.clickRevTime;
export const pipModDepth  = () => S.clickMode === 'chirp' ? S.chirpModDepth  : S.clickModDepth;
export const pipModPeriod = () => S.clickMode === 'chirp' ? S.chirpModPeriod : S.clickModPeriod;

export function rebuildClickIR() {
  if (!clickConv) return;
  clearTimeout(irTimer);
  irTimer = setTimeout(() => {
    if (clickConv) clickConv.buffer = makeImpulse(pipRevTime(), 2.5);
  }, 140);
}

export function applyReverbMix() {
  if (!harmDry) return;
  const t = audioCtx.currentTime;
  // equal-power crossfade so the total stays level as reverb comes up
  harmDry.gain.setTargetAtTime(Math.cos(S.harmReverb * Math.PI / 2), t, 0.05);
  harmWet.gain.setTargetAtTime(Math.sin(S.harmReverb * Math.PI / 2) * 0.9, t, 0.05);
  if (clickWet) clickWet.gain.setTargetAtTime(pipReverb() * 0.9, t, 0.05);
}

// Deliberately does not touch harmLevel. That param is owned by rampLevel,
// and driving one AudioParam with both setTargetAtTime and a cancelled linear
// ramp is what was producing the click.
export function applyHarmonics() {
  setParam('harmCount',  S.harmCount,   0.001);
  setParam('harmBright', 3.2 - S.harmBright * 3.0, 0.02);   // slider is brightness; the worklet wants rolloff
  setParam('harmSpread', S.harmSpread,  0.05);
  setParam('harmPanRate',S.harmPanRate, 0.05);
  setParam('clickModDepth', pipModDepth(), 0.05);
  setParam('clickModRate',  1 / pipModPeriod(), 0.05);   // control is seconds per cycle
  setParam('biDepth', S.biOn ? S.biDepth : 0, 0.05);
  setParam('biRate',  1 / S.biPeriod, 0.05);               // one full left-right pass
  setParam('biHard',  S.biHardSwitch ? 1 : 0, 0.001);
  setParam('shimDepth',  S.shimDepth,   0.05);
  setParam('shimRate',   S.shimRate,    0.05);
}

// A ramp with no preceding automation event has no defined start value and can
// jump straight to the target, which is the click you hear on the first play.
// Anchoring the current value first makes every ramp actually ramp. Mixing
// linearRamp and setTarget on one param does the same thing, so master volume
// uses only this path.
function rampVol(target, dur, startAt) {
  if (!volGain) return;
  const g = volGain.gain;
  const now = audioCtx.currentTime;
  const t = startAt !== undefined ? startAt : now;
  g.cancelScheduledValues(now);
  g.setValueAtTime(g.value, now);
  if (t > now) g.setValueAtTime(g.value, t);
  g.linearRampToValueAtTime(target, t + dur);
}

// Rebuilt whenever a chirp control moves, then shipped to the worklet. Cheap:
// a few hundred samples of trig on a control change, never in the audio thread.
//
// Delivery is acknowledged rather than assumed, and this is why.
//
// The graph is deliberately built at page load, with no user gesture, so the
// worklet is compiled long before anyone presses anything. On iOS that means
// the context is still SUSPENDED when this first runs, and a table posted to a
// worklet port on a context whose rendering thread has never run is not
// reliably delivered. The processor keeps `this.chirp = null`, `useChirp` goes
// false, and the pip quietly falls back to the plain damped sine. Nothing
// throws and nothing logs; the chirp simply never sounds.
//
// Restoring a saved setting made it permanent. settings.js assigns
// S.clickMode = 'chirp' directly instead of going through setPipShape, so on a
// phone that had chirp selected the lost table was never re-sent and the only
// way back was to toggle the mode by hand.
//
// The processor now acknowledges the table it actually holds. Anything
// unacknowledged is sent again once the context is genuinely running.
let chirpSig = null, chirpLive = null, chirpRetry = null, chirpTries = 0;

// The sample rate is part of the identity: iOS can hand back a different rate
// once the real output device wakes, and a table built for the old one is the
// wrong length and the wrong sweep.
function chirpSignature() {
  return [audioCtx.sampleRate, S.chirpLowHz, S.chirpHighHz, S.chirpComp, S.chirpTilt].join(':');
}

function sendChirp() {
  if (!node || !audioCtx) return;
  const buf = buildChirp({
    sampleRate: audioCtx.sampleRate,
    lowHz:  S.chirpLowHz,
    highHz: S.chirpHighHz,
    comp:   S.chirpComp,
    tilt:   S.chirpTilt
  });
  node.port.postMessage({ chirp: buf, sig: chirpSig }, [buf.buffer]);
  chirpTries++;
  clearTimeout(chirpRetry);
  // Only worth retrying while the context is rendering, since a suspended one
  // is the state the message gets lost in to begin with. A resume re-arms this
  // through the statechange handler below.
  if (chirpTries < 5) {
    chirpRetry = setTimeout(() => {
      chirpRetry = null;
      if (chirpLive !== chirpSig && audioCtx && audioCtx.state === 'running') sendChirp();
    }, 300);
  } else {
    chirpRetry = null;
  }
}

export function refreshChirp() {
  if (!node || !audioCtx) return;
  const sig = chirpSignature();
  // Already in hand, or a send of this exact table is still in flight with its
  // retries armed. Several paths converge here on the same gesture -- the
  // statechange, the device wake, the mode swap -- and without this they each
  // post their own copy of an identical table.
  if (sig === chirpSig && (chirpLive === sig || chirpRetry !== null)) return;
  chirpSig = sig;
  chirpTries = 0;
  sendChirp();
}

export function setParam(name, value, glide = 0.02) {
  if (!node) return;
  const prm = node.parameters.get(name);
  if (!prm) return;
  // out-of-range values get silently clamped by the engine, which hides real
  // bugs. Clamp here so the value sent is always the value meant.
  const v = Math.min(prm.maxValue, Math.max(prm.minValue, value));
  prm.setTargetAtTime(v, audioCtx.currentTime, glide);
}

// Levels get an explicit linear ramp rather than an exponential approach, so
// they start at exactly zero and arrive at exactly the target.
function rampLevel(name, target, dur = 0.25, lead = 0) {
  if (!node) return;
  const prm = node.parameters.get(name);
  if (!prm) return;
  const t = audioCtx.currentTime + lead;
  prm.cancelScheduledValues(t);
  prm.setValueAtTime(prm.value, t);
  prm.linearRampToValueAtTime(target, t + dur);
}

const levelTargets = {
  toneLevel:  () => S.audioEnabled && S.toneOn  ? S.toneVol  : 0,
  clickLevel: () => S.audioEnabled && S.clickOn ? pipVol() : 0,
  // Harmonics are the tone's own overtones, not a source of their own. With the
  // sine tone off they have nothing to be harmonics of, so they follow it down.
  // The harmonics switch keeps its own state and comes back with the tone.
  harmLevel:  () => S.audioEnabled && S.harmOn && S.toneOn ? S.harmVol : 0,
  clickSend:  () => S.audioEnabled && S.clickOn ? pipVol() * pipReverb() : 0
};

// Ramps one level only. Touching a slider used to re-ramp every level at once,
// which made the whole mix lurch whenever any one of them moved.
export function applyLevel(name, dur = 0.12, lead = 0) {
  rampLevel(name, levelTargets[name](), dur, lead);
}

// Switching the pip shape has to pass through silence.
//
// chirpOn is a step and the level is a ramp, so flipping the shape first left
// the first chirp sounding at the CLICK's level, which is around 20 dB louder.
// One very loud chirp, then the ramp caught up. At 7.5 Hz a cycle is 133 ms and
// the level ramp is 120 ms, so the overshoot lands square on the first transient
// every time.
//
// Dropping to silence, swapping at the bottom and coming back up cannot
// overshoot in either direction. It costs about 100 ms, inside which nothing
// was going to sound anyway.
export function setPipShape(mode, onSwapped) {
  const swap = () => {
    S.clickMode = mode;
    setParam('chirpOn', mode === 'chirp' ? 1 : 0, 0.001);
    if (mode === 'chirp') refreshChirp();
    applyReverbMix();
    if (clickConv) clickConv.buffer = makeImpulse(pipRevTime(), 2.5);
    setParam('clickModDepth', pipModDepth(), 0.05);
    setParam('clickModRate',  1 / pipModPeriod(), 0.05);
    if (onSwapped) onSwapped();
    applyLevel('clickLevel', 0.07);
    applyLevel('clickSend',  0.07);
  };
  if (!node || !audioCtx) { S.clickMode = mode; if (onSwapped) onSwapped(); return; }
  rampLevel('clickLevel', 0, 0.04);
  rampLevel('clickSend',  0, 0.04);
  setTimeout(swap, 55);
}

export function applyAudioShape(lead = 0) {
  for (const name of Object.keys(levelTargets)) {
    rampLevel(name, levelTargets[name](), lead ? 0.3 : 0.12, lead);
  }
  applyHarmonics();
}

export function setAudioRate(hz) { setParam('rate', hz, 0.03); }
export const setAmRate = hz => setAudioRate(hz);

// The click on first play was never our gain ramp. Starting an AudioContext
// engages the output device, and Chrome compiling a worklet module the first
// time can underrun the audio thread: both happen before any automation of
// ours applies. So the graph is built once at the safety gate, minutes before
// anyone presses space, and then never torn down. Enabling audio afterwards
// is only a gain change on an already-warm device.
//
// Split deliberately. Building the graph needs no user gesture, so it happens
// at page load and the worklet is compiled long before anyone plays anything.
// Waking the output device does need a gesture, and that wake is what clicks,
// so it is triggered on the earliest gesture available rather than on play.
export function ensureAudioGraph() {
  if (graphPromise) return graphPromise;
  graphPromise = (async () => {
    const AC = window.AudioContext || window.webkitAudioContext;
    // 'interactive' is the default and gives the smallest possible buffer, which
    // underruns while the device spins up and clicks. Nothing here needs low
    // latency, so ask for the large buffer instead.
    audioCtx = new AC({ latencyHint: 'playback' });

    volGain = audioCtx.createGain();
    volGain.gain.value = 0;
    volGain.connect(audioCtx.destination);

    await audioCtx.audioWorklet.addModule(WORKLET_URL);

    node = new AudioWorkletNode(audioCtx, 'genus', {
      numberOfInputs: 0,
      numberOfOutputs: 3,
      outputChannelCount: [2, 2, 1]   // 0: tone and pips, 1: harmonics, 2: pip reverb send
    });
    node.connect(volGain, 0);

    // The processor reports which chirp table it is actually holding, so a lost
    // post can be told apart from a delivered one.
    node.port.onmessage = e => {
      if (e.data && e.data.chirpAck === undefined) return;
      chirpLive = e.data.chirpAck;
      // Confirmed: stop the retries and let the in-flight check above clear.
      if (chirpLive === chirpSig) { clearTimeout(chirpRetry); chirpRetry = null; }
    };
    // A context that was suspended when the table was posted gets it again the
    // moment it starts rendering, at whatever sample rate it actually came up
    // with. This is the path that fixes iOS.
    audioCtx.addEventListener('statechange', () => {
      if (audioCtx.state === 'running' && chirpLive !== chirpSignature()) refreshChirp();
    });

    // Harmonics get their own dry/wet pair so reverb applies to them alone.
    // The pulse itself must stay dry or the reverb tail fills in the gaps that
    // carry the entrainment.
    harmDry = audioCtx.createGain();
    harmWet = audioCtx.createGain();
    convolver = audioCtx.createConvolver();
    convolver.buffer = makeImpulse(2.6, 2.5);
    node.connect(harmDry, 1);
    node.connect(convolver, 1);
    convolver.connect(harmWet);
    harmDry.connect(volGain);
    harmWet.connect(volGain);

    // pips get their own send into the same room, so the dry pip stays sharp
    clickWet = audioCtx.createGain();
    clickConv = audioCtx.createConvolver();
    clickConv.buffer = makeImpulse(pipRevTime(), 2.5);
    node.connect(clickConv, 2);
    clickConv.connect(clickWet);
    clickWet.connect(volGain);

    applyReverbMix();

    for (const nm of ['toneLevel','clickLevel']) {
      node.parameters.get(nm).setValueAtTime(0, audioCtx.currentTime);
    }
    setParam('rate',    S.amLinked ? S.effFreq : S.amRate, 0.001);
    setParam('carrier', S.carrierHz, 0.001);
    setParam('pipMs',   S.pipMs,     0.001);

    S.workletReady = true;
    setParam('chirpOn', S.clickMode === 'chirp' ? 1 : 0, 0.001);
    refreshChirp();
  })().catch(e => {
    console.warn('audio graph failed:', e);
    graphPromise = null;
  });
  return graphPromise;
}

// Wakes the output device. Everything is held at hard silence for a moment
// afterwards so the wake transient lands in silence rather than underneath
// whatever is about to fade in.
export async function warmDevice() {
  // nothing to wake for if audio is not in play
  if (!$('lAudio').checked && !S.audioEnabled) return;
  if (deviceWarm) return;

  // Resume FIRST, synchronously, while the gesture that called us is still the
  // browser's current user activation. Awaiting the graph before resuming spends
  // that activation: on a cold cache the worklet module takes long enough to
  // fetch and compile that the resume lands outside the gesture, Chrome leaves
  // the context suspended without throwing, and the page is silent for good.
  // That is why this only ever showed up in a fresh profile.
  if (audioCtx && audioCtx.state === 'suspended') {
    try { await audioCtx.resume(); } catch (e) {}
  }
  await ensureAudioGraph();
  if (!audioCtx) return;
  if (audioCtx.state === 'suspended') {
    try { await audioCtx.resume(); } catch (e) {}
  }
  // Truth, not intent. A resume that quietly failed has to leave this false so
  // the next gesture tries again instead of assuming the device is awake.
  deviceWarm = audioCtx.state === 'running';
  // Not every engine fires statechange on every resume, and this is the one
  // path guaranteed to run on the gesture that wakes the device.
  if (deviceWarm) refreshChirp();
}

// Several gestures can race to start audio: the gate click, the first key, and
// the start toggle itself. Without this they each schedule their own ramp and
// the shortest one wins, which is how a two second fade turned into a third of
// a second on a cold load. One start at a time; the rest await the same result.
let startPromise = null;
export function audioOn() {
  if (!startPromise) startPromise = startAudio().finally(() => { startPromise = null; });
  return startPromise;
}

async function startAudio() {
  S.audioEnabled = true;
  await warmDevice();
  await ensureAudioGraph();          // warmDevice can bail before the graph exists
  if (!S.workletReady) return;
  const firstStart = !audioHasPlayed;
  audioHasPlayed = true;
  const lead = firstStart ? 0.9 : 0;
  applyAudioShape(lead);
  // The first fade matches the visual one: the field and the sound arrive
  // together over two seconds rather than the sound landing first.
  rampVol(S.running ? S.volume : 0, firstStart ? 2.0 : 0.35, audioCtx.currentTime + lead);
}

// Deliberately keeps the context and the worklet alive. Closing and rebuilding
// them on every toggle reintroduces exactly the device-engagement click this
// is here to avoid.
export function audioOff() {
  S.audioEnabled = false;
  if (!audioCtx) return;
  applyAudioShape();
  rampVol(0, 0.25);
}

// spacebar pauses the whole experience, sound included
let hasRisen = false;
export function applyAudioGain() {
  // If audio has somehow never started, start it here rather than going quiet.
  // This is the only place that knows the session is actually running, so it is
  // the right place to be self-healing about it.
  if (!audioHasPlayed) {
    if (S.running && $('lAudio').checked) audioOn();
    return;
  }
  // The very first time the volume actually comes up it takes the same two
  // seconds the field does. After that the space bar is an instant stop and
  // start, which is what a pause should feel like.
  const dur = (S.running && !hasRisen) ? 2.0 : 0.12;
  if (S.running) hasRisen = true;
  rampVol(S.running ? S.volume : 0, dur);
}
