// The Web Audio graph: a modulated tone, a pip train, a panned harmonic stack,
// and two reverb sends. Everything sounding is generated by one AudioWorklet
// from a single sample-accurate phase accumulator (see worklet.js).
import { S } from './state.js';
import { $ } from './dom.js';
import { buildChirp } from './chirp.js';
import { chanGate, onChannelGates } from './mixgate.js';
import { scaledStrobeDepth } from './strobe-scale.js';
import { prepareAudioSession, startBackgroundKeepAlive, setBackgroundPlaying, setMediaWake } from './background.js';
import { startHeart, ctxFor, masterFor, makeWorklet, heartEngine } from './heart/route.js';
import { every, after, clear } from './ticker.js';
import { breath, breathState } from '../core/variance.js';
import { IDLE_DIAG } from '../core/idle.js';

let audioCtx = null, volGain = null, node = null;
let harmDry = null, harmWet = null, convolver = null, clickWet = null;
let clickRoom = null;
let graphPromise = null, deviceWarm = false, audioHasPlayed = false;

// The mixer's tone, harmonics and pulse meters. The worklet posts the loudest
// sample of each channel every 20 ms or so; nothing here polls, and a report
// that stops arriving reads as silence rather than as a frozen meter.
const enginePk = { tone: 0, pulse: 0, harm: 0, at: 0 };
export function enginePeaks() {
  if (!S.running || !S.audioEnabled || !audioCtx || audioCtx.state !== 'running'
      || performance.now() - enginePk.at > 200) return SILENT_PEAKS;
  return enginePk;
}
const SILENT_PEAKS = { tone: 0, pulse: 0, harm: 0 };

// Whether anyone is reading those meters. v0's mixer always wants them, so
// they default on; v1 turns them off while its mixer window is shut, which
// stops fifty messages a second (each one a small pile of garbage on the main
// thread) that nothing would look at. Remembered, so a call made before the
// worklet exists still takes effect the moment it is built.
let engineMetersOn = true;
export function setEngineMeters(on) {
  on = !!on;
  if (on === engineMetersOn) return;
  engineMetersOn = on;
  if (node) node.port.postMessage({ meters: on });
}

// The click level's variance as it plays. The dip itself lives in the
// worklet, sample by sample (worklet.js, the pips' loudness modulation), so
// the drawer's bar reads it back from there rather than keeping a second
// clock that could drift from what is heard: the share of the set level the
// dip is leaving, posted on the meters' clock while someone reads it. Nothing
// is posted with the variance at 0, nor once the readings stop being asked
// for (the first report after half a second unread switches them off again).
// A report gone quiet (a suspended context, no worklet yet) reads as no dip.
let pipDip = 1, pipDipAt = -1e9, pipDipAsked = -1e9, pipDipWanted = false;
export function pipDipRead() {
  const now = performance.now();
  pipDipAsked = now;
  if (!pipDipWanted && node) { pipDipWanted = true; node.port.postMessage({ dipWatch: true }); }
  return now - pipDipAt < 200 ? pipDip : 1;
}

// The worklet used to be a template literal turned into a Blob URL. As a real
// file it can be handed straight to addModule(). The URL is resolved against
// this module rather than the document so it keeps working from a subpath.
const WORKLET_URL = new URL('./worklet.js', import.meta.url).href;
window.__WORKLET_URL = WORKLET_URL;   // exposed so tests can render it offline
// The master room's algorithmic reverb (fdn-worklet.js, js/piano.js).
const FDN_URL = new URL('./fdn-worklet.js', import.meta.url).href;

export const isDeviceWarm = () => deviceWarm;
export const hasNode = () => !!node;
export const getContext = () => audioCtx;
// The piano hangs off the same master gain the rest of the audio uses, so the
// volume slider and the transport mute reach it without any extra wiring.
export const getMaster = () => volGain;

// ---------- impulse responses ----------
// A decaying noise burst is a perfectly serviceable reverb impulse, and it is
// far lighter to ship than an audio file. It is not free to make, though, and
// it used to be made on the main thread in one go: about 0.85 ms per second
// of stereo impulse to fill (measured in V8, warm), so a 4.5 s piano room was
// about 4 ms of one task and a 15 s one about 12. Handing the finished buffer
// to a ConvolverNode costs roughly as much again, because Chrome cuts it into
// FFT partitions right there on the main thread, and nothing can move that
// part anywhere else. Either one alone is a dropped strobe frame.
//
// So the noise is made in a worker (ir-worker.js) and transferred back; each
// finished impulse is kept by its length and decay, so asking for the same
// room again builds nothing; and the main-thread work that is left, copying
// the samples into an AudioBuffer and giving a buffer to a convolver, runs as
// separate jobs, one per idle slot. Several rooms changing in one preset then
// land across several frames instead of all in one task.
const IR_CACHE_MAX = 4;
const irCache = new Map();     // key to AudioBuffer, least recently used first
const irWaiting = new Map();   // key to the callbacks waiting on its build
const irKey = (sr, sec, decay) => sr + ':' + sec.toFixed(2) + ':' + decay;
// A rough guess at what giving a convolver this much impulse costs, used only
// to wait for an idle period with room for it. Past about 6 ms no idle period
// between strobe frames is long enough anyway, so the wait stops asking.
const assignCost = sec => Math.min(6, 0.5 + sec * 0.8);

// Hands cb an AudioBuffer holding the impulse, from the cache when it is
// there. The callback runs inside an idle slot of its own (or at once, on a
// cache hit), so whatever it does next should queue its own slot.
function getIR(ctx, sec, decay, cb) {
  const sr = ctx.sampleRate, key = irKey(sr, sec, decay);
  const hit = irCache.get(key);
  if (hit) { irCache.delete(key); irCache.set(key, hit); cb(hit); return; }
  const waiting = irWaiting.get(key);
  if (waiting) { waiting.push(cb); return; }
  irWaiting.set(key, [cb]);
  const len = Math.max(1, Math.floor(sr * sec));
  fillIR(len, decay, (l, r) => inSlot(() => {
    const buf = ctx.createBuffer(2, len, sr);
    buf.copyToChannel(l, 0);
    buf.copyToChannel(r, 1);
    irCache.set(key, buf);
    if (irCache.size > IR_CACHE_MAX) irCache.delete(irCache.keys().next().value);
    const cbs = irWaiting.get(key) || [];
    irWaiting.delete(key);
    for (const f of cbs) f(buf);
  }, 1));
}

// The worker is made on first use. If it cannot be made, or its script fails
// to load, the noise is made here instead, in slices of about a millisecond
// each with a task boundary between them, so no single task runs long.
let irWorker = null, irWorkerDead = false, irSeq = 0;
const irJobs = new Map();
const IR_SLICE = 24000;
function fillIR(len, decay, done) {
  const w = irWorkerGet();
  if (!w) { fillHere(len, decay, done); return; }
  const id = ++irSeq;
  irJobs.set(id, { len, decay, done });
  w.postMessage({ id, len, decay });
}
function irWorkerGet() {
  if (irWorker || irWorkerDead) return irWorker;
  try {
    irWorker = new Worker(new URL('./ir-worker.js', import.meta.url));
  } catch (e) {
    irWorkerDead = true;
    return null;
  }
  irWorker.onmessage = e => {
    const d = e.data, job = irJobs.get(d.id);
    if (!job) return;
    irJobs.delete(d.id);
    job.done(d.l, d.r);
  };
  irWorker.onerror = () => {
    console.warn('audio: impulse worker failed, building impulses on the main thread');
    irWorkerDead = true;
    try { irWorker.terminate(); } catch (e) {}
    irWorker = null;
    for (const job of irJobs.values()) fillHere(job.len, job.decay, job.done);
    irJobs.clear();
  };
  return irWorker;
}
function fillHere(len, decay, done) {
  const l = new Float32Array(len), r = new Float32Array(len);
  let i = 0;
  const step = () => {
    const stop = Math.min(len, i + IR_SLICE);
    for (; i < stop; i++) {
      const env = Math.pow(1 - i / len, decay);
      l[i] = (Math.random() * 2 - 1) * env;
      r[i] = (Math.random() * 2 - 1) * env;
    }
    if (i < len) setTimeout(step, 0); else done(l, r);
  };
  setTimeout(step, 0);
}

// Idle slots. Each job runs alone in an idle period of its own, the gap the
// browser leaves between one frame's work and the next frame's deadline, so
// it never lands in the middle of a frame. A job that expects to take longer
// than the time left waits for a roomier period, but only for so long: past
// SLOT_WAIT_MS it runs in the next one regardless. Where there is no
// requestIdleCallback (Safari), a short timer stands in, which still keeps
// the jobs a frame or more apart.
const SLOT_WAIT_MS = 400;
const slotJobs = [];
let slotArmed = false;
const ric = typeof requestIdleCallback === 'function' ? requestIdleCallback : null;
function inSlot(fn, cost) {
  slotJobs.push({ fn, cost, t0: performance.now() });
  armSlot();
}
function armSlot() {
  if (slotArmed || !slotJobs.length) return;
  slotArmed = true;
  if (ric) ric(runSlot, { timeout: 200 }); else setTimeout(runSlot, 20);
}
function runSlot(deadline) {
  slotArmed = false;
  const job = slotJobs[0];
  if (!job) return;
  if (deadline && !deadline.didTimeout && deadline.timeRemaining() < job.cost
      && performance.now() - job.t0 < SLOT_WAIT_MS) { armSlot(); return; }
  slotJobs.shift();
  try { job.fn(); } catch (e) { console.warn('audio: room update failed', e); }
  armSlot();
}

// ---------- preset transitions ----------
// A preset used to land every one of its changes at once, each on whatever
// short ramp its own control happened to use, and several of them were not
// ramps at all: a rounded harmonic count, a pip shape flag, a reverb impulse
// swapped under its own tail. Heard together, that was a click on every
// recall.
//
// Now a preset opens a transition around its set() calls (presets.js, in v0
// and v1 alike). While one is open, every level, every engine parameter,
// every room and every gain the music and atmosphere modules own moves along
// a straight line to its new value, and all of them arrive together at the
// end of one shared window. No dip, no fade out and back in: each number
// simply glides from where it was to where the preset puts it. Outside a
// transition nothing is different, and a slider still moves its parameter on
// the same short glide it always has.
export const PRESET_GLIDE_S = 1.5;
let glideDepth = 0, glideT1 = 0;
// What each parameter a transition moved is heading for. A call made after
// the transition's scope that asks for that same value is already being
// answered by the ramp, so it leaves the ramp alone instead of cutting it
// short (the atmosphere re-syncs its gains a few times a second while the
// drift runs, and another tab's settings arrive with a second sync behind
// them). Weakly keyed, so a node that goes away takes its entry with it.
const glideTarget = new WeakMap();

// Nested opens share the outer window, so a preset recalled from a snapshot
// (which opens one inside another) still has a single end time.
export function beginGlide(sec = PRESET_GLIDE_S) {
  if (glideDepth++ === 0 && audioCtx) glideT1 = audioCtx.currentTime + sec;
}
export function endGlide() { if (glideDepth > 0) glideDepth--; }

// The end of the open transition, or 0 when none is open. Work that finishes
// after the transition's synchronous scope (an impulse built on a timer, a
// recording that has to load, an audio start that awaits the device) takes
// this with it and hands it back to continueGlide when it gets there.
export const glideEnd = () => (glideDepth > 0 && audioCtx) ? glideT1 : 0;

// Runs fn as part of a transition ending at `end`, provided enough of it is
// left to be worth gliding over; otherwise fn runs as an ordinary change.
export function continueGlide(end, fn) {
  if (glideDepth > 0 || !audioCtx || !(end > audioCtx.currentTime + 0.05)) { fn(); return; }
  const prev = glideT1;
  glideDepth = 1; glideT1 = end;
  try { fn(); } finally { glideDepth = 0; glideT1 = Math.max(prev, end); }
}

// Holds a parameter at the value it has right now and drops everything
// queued after it, so the next ramp starts from where the sound actually is.
function anchorParam(prm, t) {
  const v = prm.value;
  prm.cancelScheduledValues(t);
  prm.setValueAtTime(v, t);
}
// The same, for a caller that is about to write its own automation onto a
// parameter (the atmosphere's drift schedules whole curves). The ramp it
// replaces is no longer the parameter's destination, so it is forgotten too.
export function holdParam(prm, t) {
  glideTarget.delete(prm);
  anchorParam(prm, t);
}

// Moves one AudioParam to `value`. Inside a transition: a straight line to
// the end of the window. Otherwise: the caller's usual exponential approach
// with time constant tc, after dropping any transition ramp still running on
// it, because a setTarget laid among a ramp's events is pulled back to the
// ramp's end value when that event comes due.
export function glideParam(prm, value, tc) {
  if (!audioCtx || !prm) return;
  const now = audioCtx.currentTime;
  if (glideDepth > 0) {
    anchorParam(prm, now);
    prm.linearRampToValueAtTime(value, glideT1);
    glideTarget.set(prm, value);
    return;
  }
  // Only a parameter still carrying a transition ramp needs that ramp cut
  // away first. One already cut free takes a plain setTarget, which matters
  // for the linked pulse rate: the strobe's own glide calls this on every
  // frame of the window, and anchoring each time was three automation calls a
  // frame, and a step back to the last rendered value, instead of one.
  if (now < glideT1) {
    const heading = glideTarget.get(prm);
    if (heading === value) return;
    if (heading !== undefined) {
      glideTarget.delete(prm);
      anchorParam(prm, now);
    }
  }
  prm.setTargetAtTime(value, now, tc);
}

// ---------- rooms ----------
// A reverb whose impulse can change without cutting its tail. Replacing a
// ConvolverNode's buffer drops everything still ringing in it at once, which
// is a click and then a hole where the tail was. So each room is two
// convolvers side by side: a new impulse goes into the idle one and the two
// are crossfaded in straight lines, over the transition window during a
// preset and over ROOM_XFADE_S otherwise. Once a fade is done the retired
// side is unplugged from the input, so the spare convolver costs nothing
// while it waits. Shared by the pip send here and the piano, clouds and
// atmosphere rooms.
//
// A room is described rather than handed a buffer: sec reads its length from
// the settings, decay is fixed. Each side remembers which impulse it holds,
// so a request for the one already playing does nothing at all, and one for
// the impulse the spare side still holds (a preset recalled and then undone)
// crossfades straight back to it without building or partitioning anything.
// Even the first impulse arrives this way, faded in from an empty room, so
// making a room never builds anything in the task that asked for it.
const ROOM_XFADE_S = 0.3;
export function createRoom(ctx, sec, decay) {
  const input = ctx.createGain(), output = ctx.createGain();
  const side = () => {
    const c = ctx.createConvolver(), g = ctx.createGain();
    g.gain.value = 0;
    c.connect(g); g.connect(output);
    return { c, g, key: '' };
  };
  const room = { ctx, sec, decay, input, output, live: side(), idle: side(),
                 target: '', tok: 0, busyUntil: 0, timer: null, gen: 0 };
  roomWant(room, 0);
  return room;
}

// Asks the room for the impulse its settings now describe, after delayMs (a
// drag is debounced, so only the last of a burst is built). The settings are
// read again when the delay runs out, so the last value is the one heard. The
// transition's end is taken now, while it is still open. A setting that names
// the impulse the room already has, or is already on its way to, returns
// here and costs nothing, which is every preset that leaves reverb time alone.
export function swapRoom(room, delayMs = 0) {
  if (!room) return;
  clearTimeout(room.timer);
  room.timer = null;
  if (roomKey(room) === room.target) return;
  // The transition's end is a time on this module's context, whose clock a
  // Heart context keeps too (js/heart/heart.js). A room built in another
  // native one (Live Sound's, js/livesound.js) keeps a clock of its own, so
  // it takes the ordinary crossfade rather than a time it cannot read.
  const end = room.ctx === audioCtx || room.ctx.isHeart ? glideEnd() : 0;
  room.timer = setTimeout(() => { room.timer = null; roomWant(room, end); }, delayMs);
}
const roomKey = room => irKey(room.ctx.sampleRate, room.sec(), room.decay);

// tok marks the newest request, so a build that finishes after the settings
// have moved on is dropped rather than faded in.
function roomWant(room, end) {
  const sec = room.sec(), key = irKey(room.ctx.sampleRate, sec, room.decay);
  if (key === room.target) return;
  room.target = key;
  const tok = ++room.tok;
  if (key === room.live.key) return;
  if (key === room.idle.key) { inSlot(() => roomPlace(room, tok, null, end), 0.5); return; }
  getIR(room.ctx, sec, room.decay, buf =>
    inSlot(() => roomPlace(room, tok, buf, end), assignCost(sec)));
}

// On Heart a gesture anchored at currentTime is heard from the context's
// presentTime, a lookahead on (js/heart/nodes.js, late gestures), while an
// impulse handed to a convolver lands at once. So a crossfade's end is kept
// as the time it is heard, and the next one waits for the clock to pass it
// before touching the side it faded out; natively the two times are one.
function roomPlace(room, tok, buf, end) {
  if (room.tok !== tok) return;
  const ctx = room.ctx, now = ctx.currentTime;
  // One crossfade at a time: until the last one lands, the idle side is
  // still fading out and has to be left alone.
  if (now < room.busyUntil) {
    setTimeout(() => inSlot(() => roomPlace(room, tok, buf, end), buf ? assignCost(buf.duration) : 0.5),
      Math.max(50, (room.busyUntil - now) * 1000 + 20));
    return;
  }
  const incoming = room.idle, outgoing = room.live;
  if (incoming.key !== room.target) {
    // Expected the spare side to hold it and it does not: build it after all.
    if (!buf) { room.target = ''; roomWant(room, end); return; }
    // The one expensive line: Chrome partitions the impulse for FFT right
    // here, which is why it runs alone in an idle slot.
    incoming.c.buffer = buf;
    incoming.key = room.target;
  }
  room.input.connect(incoming.c);
  const dur = Math.max(ROOM_XFADE_S, end - now);
  const gi = incoming.g.gain;
  gi.cancelScheduledValues(now);
  gi.setValueAtTime(0, now);
  gi.linearRampToValueAtTime(1, now + dur);
  anchorParam(outgoing.g.gain, now);
  outgoing.g.gain.linearRampToValueAtTime(0, now + dur);
  room.live = incoming; room.idle = outgoing;
  room.busyUntil = (ctx.presentTime ?? now) + dur;
  const gen = ++room.gen;
  setTimeout(() => {
    if (room.gen !== gen) return;
    try { room.input.disconnect(outgoing.c); } catch (e) {}
  }, (room.busyUntil - now) * 1000 + 100);
}

// The active pip shape owns its own level and room. Everything downstream reads
// through these three, so switching mode swaps the whole set at once and no
// chirp control can write into a click value or the reverse.
const trimGain = () => Math.pow(10, S.pipTrimDb / 20);
export const pipVol     = () => Math.min(1, (S.clickMode === 'chirp' ? S.chirpVol : S.clickVol) * trimGain());
export const pipReverb  = () => S.clickMode === 'chirp' ? S.chirpReverb  : S.clickReverb;
export const pipRevTime = () => S.clickMode === 'chirp' ? S.chirpRevTime : S.clickRevTime;
export const pipModDepth  = () => S.clickMode === 'chirp' ? S.chirpModDepth  : S.clickModDepth;
export const pipModPeriod = () => S.clickMode === 'chirp' ? S.chirpModPeriod : S.clickModPeriod;

// Debounced, and crossfaded into the pip room rather than swapped under it.
// Nothing is built when the live shape's reverb time is the one already in
// the room, which is most shape changes and every preset that leaves it be.
export function rebuildClickIR() {
  swapRoom(clickRoom, 140);
}

export function applyReverbMix() {
  if (!harmDry) return;
  // equal-power crossfade so the total stays level as reverb comes up
  glideParam(harmDry.gain, Math.cos(S.harmReverb * Math.PI / 2), 0.05);
  glideParam(harmWet.gain, Math.sin(S.harmReverb * Math.PI / 2) * 0.9, 0.05);
}

// Deliberately does not touch harmLevel. That param is owned by rampLevel,
// and driving one AudioParam with both setTargetAtTime and a cancelled linear
// ramp is what was producing the click.
export function applyHarmonics() {
  setParam('harmCount',  S.harmCount,   0.001);
  setParam('harmBright', 3.2 - S.harmBright * 3.0, 0.02);   // slider is brightness; the worklet wants rolloff
  setParam('harmSpread', S.harmSpread,  0.05);
  setParam('harmPanRate',S.harmPanRate, 0.05);
  setParam('clickModDepth', pipModDepth(), 0.05);
  setParam('clickModRate',  1 / pipModPeriod(), 0.05);   // control is seconds per cycle
  setParam('biDepth', S.biOn ? S.biDepth : 0, 0.05);
  setParam('biRate',  1 / S.biPeriod, 0.05);               // one full left-right pass
  setParam('biHard',  S.biHardSwitch ? 1 : 0, 0.001);
  setParam('shimDepth',  S.shimDepth,   0.05);
  setParam('shimRate',   S.shimRate,    0.05);
  applyPipLpf();
}

// The pip train's lowpass sweep (worklet.js). The worklet owns the motion and
// the glide; this only hands it the settings.
export function applyPipLpf() {
  setParam('lpfOn',     S.pipLpfOn ? 1 : 0, 0.001);
  setParam('lpfLo',     S.pipLpfLo,     0.05);
  setParam('lpfHi',     S.pipLpfHi,     0.05);
  setParam('lpfPeriod', S.pipLpfPeriod, 0.001);
  setParam('lpfQ',      S.pipLpfQ,      0.05);
  setParam('lpfWander', S.pipLpfWander, 0.05);
}

// A ramp with no preceding automation event has no defined start value and can
// jump straight to the target, which is the click you hear on the first play.
// Anchoring the current value first makes every ramp actually ramp. Mixing
// linearRamp and setTarget on one param does the same thing, so master volume
// uses only this path.
//
// Inside a transition the ramp runs to the end of the window instead of over
// dur, so the master glides with everything else. A start held for later
// (the first fade in) is its own business and keeps its own timing.
function rampVol(target, dur, startAt) {
  if (!volGain) return;
  const g = volGain.gain;
  const now = audioCtx.currentTime;
  if (startAt === undefined) {
    if (glideDepth > 0) {
      anchorParam(g, now);
      g.linearRampToValueAtTime(target, glideT1);
      glideTarget.set(g, target);
      masterTo(target, glideT1);
      return;
    }
    if (now < glideT1 && glideTarget.get(g) === target) return;
  }
  glideTarget.delete(g);
  const t = startAt !== undefined ? startAt : now;
  g.cancelScheduledValues(now);
  g.setValueAtTime(g.value, now);
  if (t > now) g.setValueAtTime(g.value, t);
  g.linearRampToValueAtTime(target, t + dur);
  masterTo(target, t + dur);
}

// Rebuilt whenever a chirp control moves, then shipped to the worklet. Cheap:
// a few hundred samples of trig on a control change, never in the audio thread.
//
// Delivery is acknowledged rather than assumed, and this is why.
//
// The graph is deliberately built at page load, with no user gesture, so the
// worklet is compiled long before anyone presses anything. On iOS that means
// the context is still SUSPENDED when this first runs, and a table posted to a
// worklet port on a context whose rendering thread has never run is not
// reliably delivered. The processor keeps `this.chirp = null`, `useChirp` goes
// false, and the pip quietly falls back to the plain damped sine. Nothing
// throws and nothing logs; the chirp simply never sounds.
//
// Restoring a saved setting made it permanent. settings.js assigns
// S.clickMode = 'chirp' directly instead of going through setPipShape, so on a
// phone that had chirp selected the lost table was never re-sent and the only
// way back was to toggle the mode by hand.
//
// The processor now acknowledges the table it actually holds. Anything
// unacknowledged is sent again once the context is genuinely running.
let chirpSig = null, chirpLive = null, chirpRetry = null, chirpTries = 0;

// The sample rate is part of the identity: iOS can hand back a different rate
// once the real output device wakes, and a table built for the old one is the
// wrong length and the wrong sweep.
function chirpSignature() {
  return [genusRate(), S.chirpLowHz, S.chirpHighHz, S.chirpComp, S.chirpTilt].join(':');
}
// The rate the engine renders at, which is the rate its table is built for.
// Natively that is the context's own, the one iOS can change on wake. On
// Heart it is the engine's, fixed when Heart started (js/heart/engine.js).
const genusRate = () => (node.context && node.context.isHeart ? heartEngine().sampleRate : audioCtx.sampleRate);

// The worklet crossfades from the table it has to the new one rather than
// swapping it under a chirp that is sounding: over what is left of the window
// during a transition, and over CHIRP_XF_S for a slider or a resend.
const CHIRP_XF_S = 0.03;
function sendChirp() {
  if (!node || !audioCtx) return;
  const buf = buildChirp({
    sampleRate: genusRate(),
    lowHz:  S.chirpLowHz,
    highHz: S.chirpHighHz,
    comp:   S.chirpComp,
    tilt:   S.chirpTilt
  });
  const end = glideEnd();
  const xf = end ? Math.max(CHIRP_XF_S, end - audioCtx.currentTime) : CHIRP_XF_S;
  node.port.postMessage({ chirp: buf, sig: chirpSig, xf }, [buf.buffer]);
  chirpTries++;
  clearTimeout(chirpRetry);
  // Only worth retrying while the context is rendering, since a suspended one
  // is the state the message gets lost in to begin with. A resume re-arms this
  // through the statechange handler below.
  if (chirpTries < 5) {
    chirpRetry = setTimeout(() => {
      chirpRetry = null;
      if (chirpLive !== chirpSig && audioCtx && audioCtx.state === 'running') sendChirp();
    }, 300);
  } else {
    chirpRetry = null;
  }
}

export function refreshChirp() {
  if (!node || !audioCtx) return;
  const sig = chirpSignature();
  // Already in hand, or a send of this exact table is still in flight with its
  // retries armed. Several paths converge here on the same gesture -- the
  // statechange, the device wake, the mode swap -- and without this they each
  // post their own copy of an identical table.
  if (sig === chirpSig && (chirpLive === sig || chirpRetry !== null)) return;
  chirpSig = sig;
  chirpTries = 0;
  sendChirp();
}

export function setParam(name, value, glide = 0.02) {
  if (!node) return;
  const prm = node.parameters.get(name);
  if (!prm) return;
  // out-of-range values get silently clamped by the engine, which hides real
  // bugs. Clamp here so the value sent is always the value meant.
  const v = Math.min(prm.maxValue, Math.max(prm.minValue, value));
  // glide is the time constant used outside a transition; inside one the
  // parameter runs in a straight line to the end of the window
  glideParam(prm, v, glide);
}

// Levels get an explicit linear ramp rather than an exponential approach, so
// they start at exactly zero and arrive at exactly the target. Inside a
// transition the ramp runs to the end of the window instead of over dur.
function rampLevel(name, target, dur = 0.25, lead = 0) {
  if (!node) return;
  const prm = node.parameters.get(name);
  if (!prm) return;
  const now = audioCtx.currentTime;
  if (!lead) {
    if (glideDepth > 0) {
      anchorParam(prm, now);
      prm.linearRampToValueAtTime(target, glideT1);
      glideTarget.set(prm, target);
      return;
    }
    if (now < glideT1 && glideTarget.get(prm) === target) return;
  }
  glideTarget.delete(prm);
  const t = now + lead;
  prm.cancelScheduledValues(t);
  prm.setValueAtTime(prm.value, t);
  prm.linearRampToValueAtTime(target, t + dur);
}

// Each level carries its channel's mix gate (mixgate.js), so mute and solo
// ride the same ramp as every other level change. The pulse's reverb send is
// gated with the pulse itself, so a muted pulse leaves nothing feeding the
// room and no tail behind it; the harmonics' room is fed from harmLevel's
// output, so gating that level silences their reverb too.
//
// The click and the chirp are two voices in the worklet with a level and a
// send each. Only the live shape's pair is ever above zero, so a change of
// shape is the one pair ramping down while the other ramps up.
//
// Each level is two stages multiplied: the voice's own level (the drawer and
// v1's Levels window, the backstage pre-mix, which sets its ceiling) times
// the Music window's performance trim for it, S.musTone for the tone and its
// harmonics together and S.musPulse for the pulse, dry and send, click or
// chirp. A trim of 1 plays exactly what the level says. v0 never sets the
// trims, so an unset one reads as 1.
//
// The tone's level takes its variance's dip as a third stage (the tone's two
// variances, below), so every move of it lands on the breath as it stands.
const perfTrim = v => Number.isFinite(v) ? Math.max(0, Math.min(1, v)) : 1;
const shapeVol  = chirp => Math.min(1, (chirp ? S.chirpVol : S.clickVol) * trimGain()) * perfTrim(S.musPulse ?? 1);
const shapeLive = chirp => S.audioEnabled && S.clickOn && (S.clickMode === 'chirp') === chirp;
const levelTargets = {
  toneLevel:  () => S.audioEnabled && S.toneOn  ? S.toneVol * (1 - toneVolDip) * perfTrim(S.musTone ?? 1) * chanGate('fund') : 0,
  clickLevel: () => shapeLive(false) ? shapeVol(false) * chanGate('pulse') : 0,
  chirpLevel: () => shapeLive(true)  ? shapeVol(true)  * chanGate('pulse') : 0,
  // Harmonics are the tone's own overtones, not a source of their own. With the
  // sine tone off they have nothing to be harmonics of, so they follow it down.
  // The harmonics switch keeps its own state and comes back with the tone.
  harmLevel:  () => S.audioEnabled && S.harmOn && S.toneOn ? S.harmVol * perfTrim(S.musTone ?? 1) * chanGate('harm') : 0,
  clickSend:  () => shapeLive(false) ? shapeVol(false) * S.clickReverb * chanGate('pulse') : 0,
  chirpSend:  () => shapeLive(true)  ? shapeVol(true)  * S.chirpReverb * chanGate('pulse') : 0
};
const LEVEL_NAMES = Object.keys(levelTargets);
// Every caller still speaks of the pulse as clickLevel and clickSend, one
// level and one send whatever the shape, so each of those names moves its
// chirp twin with it.
const LEVEL_TWIN = { clickLevel: 'chirpLevel', clickSend: 'chirpSend' };

// Ramps one level only. Touching a slider used to re-ramp every level at once,
// which made the whole mix lurch whenever any one of them moved.
export function applyLevel(name, dur = 0.12, lead = 0) {
  rampLevel(name, levelTargets[name](), dur, lead);
  const twin = LEVEL_TWIN[name];
  if (twin) rampLevel(twin, levelTargets[twin](), dur, lead);
}

// A mute or solo anywhere in the mix re-ramps the four engine levels. Each
// goes through applyLevel, so the gate glides in on the same short linear
// ramp a fader move does and never steps.
onChannelGates(() => {
  applyLevel('toneLevel');
  applyLevel('harmLevel');
  applyLevel('clickLevel');
  applyLevel('clickSend');
});

// Switching the pip shape is a crossfade between the two voices.
//
// It used to have to pass through silence. With one shared level and a shape
// flag, the flag was a step and the level a ramp, so the first chirp after a
// switch sounded at the CLICK's level, around 20 dB louder, and the fix was
// to dip to nothing, swap at the bottom and come back up. That dip is what a
// preset heard as a hole. Now each shape has its own level (worklet.js): the
// click ramps from its level to zero while the chirp ramps from zero to its
// own, so neither can pass through the other's level and there is nothing
// left for a dip to protect against. Inside a transition the whole exchange
// rides the window; outside, it takes SHAPE_XFADE_S, about what the dip took.
const SHAPE_XFADE_S = 0.1;
export function setPipShape(mode, onSwapped) {
  S.clickMode = mode;
  if (!node || !audioCtx) { if (onSwapped) onSwapped(); return; }
  // The table goes first so it is usually in hand before the chirp's level
  // leaves zero; until it lands, the chirp voice plays the click's sine, as
  // it always has.
  if (mode === 'chirp') refreshChirp();
  applyReverbMix();
  rebuildClickIR();
  setParam('clickModDepth', pipModDepth(), 0.05);
  setParam('clickModRate',  1 / pipModPeriod(), 0.05);
  if (onSwapped) onSwapped();
  applyLevel('clickLevel', SHAPE_XFADE_S);
  applyLevel('clickSend',  SHAPE_XFADE_S);
}

export function applyAudioShape(lead = 0) {
  for (let i = 0; i < LEVEL_NAMES.length; i++) {
    const name = LEVEL_NAMES[i];
    rampLevel(name, levelTargets[name](), lead ? 0.3 : 0.12, lead);
  }
  applyHarmonics();
  applyAmOn();
}

// The pulse rate the engine's phase runs at while free. Linked, the engine
// takes its phase from the strobe's own formula instead (worklet.js,
// flashAlign), which js/strobe-am.js posts it; that file registers here
// (watchEngine) and is told when the node is made and whenever the rate is
// set, since every change of the link (v1's Audio mode, v0's Link and Free
// buttons) sets the rate straight after, so the switch reaches the engine
// at once rather than at strobe-am's next tick.
let engineWatch = null;
export function watchEngine(fn) {
  engineWatch = fn;
  if (node && S.workletReady) fn(node);
}
function tellEngineWatch() {
  if (engineWatch && node && S.workletReady) engineWatch(node);
}
export function setAudioRate(hz) { setParam('rate', hz, 0.03); tellEngineWatch(); }
export const setAmRate = hz => setAudioRate(hz);

// The Amplitude modulation switch. Off holds the tone and harmonics steady
// at the pulse's peak by taking the envelope's depth to zero; the rate is
// left alone, so the linked strobe and a free Pulse rate keep steering it
// underneath and the pips, timed from the same phase, carry on exactly as
// before. Glided both ways (and along a preset's window), so it never clicks.
//
// On, the depth is the tone's Vary with strobe (S.toneStrobeAm, 1 when
// unset, the full pulse it always had) times the master strobe, the same
// scaledStrobeDepth every other Vary with strobe stage goes through
// (js/strobe-am.js): the master brought to 0 leaves the tone steady, as it
// leaves the drone, the choir, the clouds and the sequencer. The pulse is
// still the engine's own envelope, already on the flash when linked, so no
// second stage taps it and nothing pulses twice. The master's control calls
// this again whenever it moves (schema-audio.js, strobeScale). The depth's
// variance dips the tone's setting before the master scales it, as every
// stage's does (strobe-am.js applyDepth).
const toneAmDepth = () => S.amModOn === false ? 0
  : scaledStrobeDepth((typeof S.toneStrobeAm === 'number' ? S.toneStrobeAm : 1) * (1 - toneAmDip));
export function applyAmOn(tc = 0.05) { syncToneBreath(); setParam('amDepth', toneAmDepth(), tc); }

// ---------- the tone's two variances ----------
// Its Level and its Vary with strobe each breathe by the app's one law
// (core/variance.js breath) on the audio clock, sinusoid or walk by their
// Behavior toggles (schema-audio.js): each eases down from its setting by up
// to its variance's share and back, once a speed cycle, never above it. The
// dips multiply in where the targets are worked out (levelTargets.toneLevel
// and toneAmDepth above), so a fader, a mute, a preset or the master strobe
// lands on the breath as it stands, and a 10 Hz timer, running only while
// either variance is above 0 and the engine is built, carries the two params
// along between: the level on a straight ramp a step long, the depth on a
// setTarget of the same length, so each step blends into the next and
// nothing zips. Each is written only when its target has moved, so a silent
// tone costs no automation at all. A param a preset's transition is still
// carrying (glideTarget) is left to land first and picked up on the tick
// after; cutting in would turn the preset's glide into a jump. Heart's
// genus takes these same calls (js/heart/params.js), so both engines
// breathe alike.
const toneVolB = breathState(), toneAmB = breathState();
let toneVolDip = 0, toneAmDip = 0, toneTimer = 0, toneVolSent = -1, toneAmSent = -1;
const varAmt = v => Math.max(0, Math.min(1, +v || 0));
function breatheTone(now) {
  toneVolDip = breath(toneVolB, varAmt(S.toneVolVar), S.toneVolPeriod, now);
  toneAmDip = breath(toneAmB, varAmt(S.toneStrobeAmVar), S.toneStrobeAmPeriod, now);
}
function toneBreathTick() {
  if (!node || !audioCtx) { syncToneBreath(); return; }
  const now = audioCtx.currentTime;
  breatheTone(now);
  const lvl = levelTargets.toneLevel(), dep = toneAmDepth();
  if (lvl !== toneVolSent && !(now < glideT1 && glideTarget.has(node.parameters.get('toneLevel')))) {
    toneVolSent = lvl;
    rampLevel('toneLevel', lvl, 0.1);
  }
  if (dep !== toneAmSent && !(now < glideT1 && glideTarget.has(node.parameters.get('amDepth')))) {
    toneAmSent = dep;
    setParam('amDepth', dep, 0.1);
  }
}
function syncToneBreath() {
  const need = !!node && (varAmt(S.toneVolVar) > 0 || varAmt(S.toneStrobeAmVar) > 0);
  if (need && !toneTimer) { toneVolSent = toneAmSent = -1; toneTimer = every(100, toneBreathTick); }
  else if (!need && toneTimer) { clear(toneTimer); toneTimer = 0; }
}
// The variance rows' engine hook (schema-audio.js): the breath stepped to
// now, so an amount brought to 0 hands the settings straight back, then both
// params on their usual glides and the timer started or stopped to suit.
export function applyToneBreath() {
  if (audioCtx) breatheTone(audioCtx.currentTime);
  applyLevel('toneLevel');
  applyAmOn();
}
// The share of each setting its dip is leaving right now, 1 at the top of
// the breath: the drawer's lit bars (core/audio-mirror.js, on either thread).
export const toneVolMul = () => 1 - toneVolDip;
export const toneAmMul = () => 1 - toneAmDip;

// The click on first play was never our gain ramp. Starting an AudioContext
// engages the output device, and Chrome compiling a worklet module the first
// time can underrun the audio thread: both happen before any automation of
// ours applies. So the graph is built once at the safety gate, minutes before
// anyone presses space, and then never torn down. Enabling audio afterwards
// is only a gain change on an already-warm device.
//
// Split deliberately. Building the graph needs no user gesture, so it happens
// at page load and the worklet is compiled long before anyone plays anything.
// Waking the output device does need a gesture, and that wake is what clicks,
// so it is triggered on the earliest gesture available rather than on play.
export function ensureAudioGraph() {
  if (graphPromise) return graphPromise;
  prepareAudioSession();   // media, not ambient sound, so a locked phone plays on
  graphPromise = (async () => {
    const AC = window.AudioContext || window.webkitAudioContext;
    // 'interactive' is the default and gives the smallest possible buffer, which
    // underruns while the device spins up and clicks. Nothing here needs low
    // latency, so ask for the large buffer instead.
    audioCtx = new AC({ latencyHint: 'playback' });
    setMediaWake(resumeAudio);

    volGain = audioCtx.createGain();
    volGain.gain.value = 0;
    volGain.connect(audioCtx.destination);

    // The reverb's module loads beside the engine's; if it fails, the
    // Algorithmic reverb type stays on convolution (piano.js) and nothing
    // else notices.
    await Promise.all([
      audioCtx.audioWorklet.addModule(WORKLET_URL),
      audioCtx.audioWorklet.addModule(FDN_URL).catch(e => console.warn('audio: algorithmic reverb failed to load', e))
    ]);
    // Heart, the engine that renders ahead in workers, starts here for the
    // families flagged to use it (js/heart/route.js), playing into volGain
    // so the volume and the pause gate stay these. With no family flagged
    // it loads nothing and does nothing.
    await startHeart(audioCtx, volGain);

    // The genus family (this engine, the harmonics' room and the pips' room)
    // builds on the context route.js hands it and ends at its master: on
    // Heart, the island 'genus' and Heart's master bus, which plays into
    // volGain; otherwise this context and volGain itself. Times are still
    // read from audioCtx, whose clock a Heart context keeps.
    const gctx = ctxFor('genus'), out = masterFor('genus');
    node = makeWorklet(gctx, 'genus', {
      numberOfInputs: 0,
      numberOfOutputs: 3,
      outputChannelCount: [2, 2, 1]   // 0: tone and pips, 1: harmonics, 2: pip reverb send
    });
    // Each output passes through a pause gate before anything else, ahead of
    // the dry and wet splits, so a pause stops the worklet feeding its rooms
    // as well as the speakers and the tails are left to ring out (see the
    // pause gate, after applyAudioGain).
    const srcGate = [0, 1, 2].map(i => {
      const g = gctx.createGain();
      sourceGate(g.gain);
      node.connect(g, i);
      return g;
    });
    srcGate[0].connect(out);
    if (!engineMetersOn) node.port.postMessage({ meters: false });

    // The processor reports which chirp table it is actually holding, so a lost
    // post can be told apart from a delivered one.
    node.port.onmessage = e => {
      const d = e.data;
      if (d && d.peaks) {
        // three plain fields rather than an array destructured through the
        // iterator protocol: this arrives every 20 ms
        enginePk.tone = d.tone; enginePk.pulse = d.pulse; enginePk.harm = d.harm;
        enginePk.at = performance.now();
        return;
      }
      if (d && d.dip !== undefined) {
        pipDip = d.dip; pipDipAt = performance.now();
        if (pipDipAt - pipDipAsked > 500) { pipDipWanted = false; node.port.postMessage({ dipWatch: false }); }
        return;
      }
      if (e.data && e.data.chirpAck === undefined) return;
      chirpLive = e.data.chirpAck;
      // Confirmed: stop the retries and let the in-flight check above clear.
      if (chirpLive === chirpSig) { clearTimeout(chirpRetry); chirpRetry = null; }
    };
    // A context that was suspended when the table was posted gets it again the
    // moment it starts rendering, at whatever sample rate it actually came up
    // with. This is the path that fixes iOS.
    audioCtx.addEventListener('statechange', () => {
      if (audioCtx.state === 'running' && chirpLive !== chirpSignature()) refreshChirp();
    });

    // Harmonics get their own dry/wet pair so reverb applies to them alone.
    // The pulse itself must stay dry or the reverb tail fills in the gaps that
    // carry the entrainment.
    harmDry = gctx.createGain();
    harmWet = gctx.createGain();
    // Its impulse never changes, but it is still built off the main thread
    // and handed over in an idle slot (see impulse responses, above); the
    // harmonics' wet side is simply silent until it lands.
    convolver = gctx.createConvolver();
    getIR(gctx, HARM_IR_S, 2.5, buf => inSlot(() => { convolver.buffer = buf; }, assignCost(HARM_IR_S)));
    srcGate[1].connect(harmDry);
    srcGate[1].connect(convolver);
    convolver.connect(harmWet);
    harmDry.connect(out);
    harmWet.connect(out);

    // pips get their own send into a room of their own, so the dry pip stays
    // sharp; a pair of convolvers, so its impulse can change under a tail
    // The reverb amount rides the send (clickSend, chirpSend), once, so each
    // shape keeps its own amount through a swap; the room's return is a fixed
    // trim, as every room's feed is a send and its return a constant.
    clickWet = gctx.createGain();
    clickWet.gain.value = 0.9;
    clickRoom = createRoom(gctx, pipRevTime, 2.5);
    srcGate[2].connect(clickRoom.input);
    clickRoom.output.connect(clickWet);
    clickWet.connect(out);

    applyReverbMix();

    for (const nm of ['toneLevel','clickLevel','chirpLevel']) {
      node.parameters.get(nm).setValueAtTime(0, audioCtx.currentTime);
    }
    setParam('rate',    S.amLinked ? S.effFreq : S.amRate, 0.001);
    setParam('carrier', S.carrierHz, 0.001);
    setParam('pipMs',   S.pipMs,     0.001);
    applyAmOn(0.001);

    S.workletReady = true;
    tellEngineWatch();
    refreshChirp();
  })().catch(e => {
    console.warn('audio graph failed:', e);
    graphPromise = null;
  });
  return graphPromise;
}

// Whether the Audio layer is switched on. v0 keeps that in its checkbox;
// v1 has no DOM and keeps it in S.audioOnBoot (unset means on, as the
// checkbox ships checked). Reading through here lets both share this module.
function audioLayerChecked() {
  const el = $('lAudio');
  return el ? el.checked : S.audioOnBoot !== false;
}

// Wakes the output device. Everything is held at hard silence for a moment
// afterwards so the wake transient lands in silence rather than underneath
// whatever is about to fade in.
export async function warmDevice() {
  // nothing to wake for if audio is not in play
  if (!audioLayerChecked() && !S.audioEnabled) return;
  // The lock screen's silent loop takes its first play from this same
  // gesture, before anything below awaits (js/background.js).
  startBackgroundKeepAlive();
  if (deviceWarm) return;

  // Resume FIRST, synchronously, while the gesture that called us is still the
  // browser's current user activation. Awaiting the graph before resuming spends
  // that activation: on a cold cache the worklet module takes long enough to
  // fetch and compile that the resume lands outside the gesture, Chrome leaves
  // the context suspended without throwing, and the page is silent for good.
  // That is why this only ever showed up in a fresh profile.
  if (audioCtx && audioCtx.state === 'suspended') {
    try { await audioCtx.resume(); } catch (e) {}
  }
  await ensureAudioGraph();
  if (!audioCtx) return;
  if (audioCtx.state === 'suspended') {
    try { await audioCtx.resume(); } catch (e) {}
  }
  // Truth, not intent. A resume that quietly failed has to leave this false so
  // the next gesture tries again instead of assuming the device is awake.
  deviceWarm = audioCtx.state === 'running';
  // Not every engine fires statechange on every resume, and this is the one
  // path guaranteed to run on the gesture that wakes the device.
  if (deviceWarm) refreshChirp();
}

// Media Session's play (the lock screen, a headset) starts the transport,
// and the context iOS suspended while the screen was locked has to wake with
// it: nothing else on that path resumes it (js/background.js).
// Every gesture while the sound is meant to be heard calls it too, which is
// what starts a context an interruption (a call, Siri, another app) left
// 'interrupted' or suspended; the session type goes first, as it may have
// been started over.
function resumeAudio() {
  if (audioCtx && audioCtx.state !== 'running' && audioCtx.state !== 'closed') {
    prepareAudioSession();
    audioCtx.resume().catch(() => {});
  }
}

// Several gestures can race to start audio: the gate click, the first key, and
// the start toggle itself. Without this they each schedule their own ramp and
// the shortest one wins, which is how a two second fade turned into a third of
// a second on a cold load. One start at a time; the rest await the same result.
let startPromise = null;
export function audioOn() {
  if (!startPromise) startPromise = startAudio().finally(() => { startPromise = null; });
  return startPromise;
}

async function startAudio() {
  S.audioEnabled = true;
  followBackground();
  // A preset that switches audio on opens its transition before this awaits
  // anything, and the ramps below come after; the window's end carries over.
  const end = glideEnd();
  await warmDevice();
  await ensureAudioGraph();          // warmDevice can bail before the graph exists
  if (!S.workletReady) return;
  const firstStart = !audioHasPlayed;
  audioHasPlayed = true;
  const lead = firstStart ? 0.9 : 0;
  closeAt = 0;   // this ramp replaces any tail the master was holding for
  setSources(S.running);
  continueGlide(end, () => {
    applyAudioShape(lead);
    // The first fade matches the visual one: the field and the sound arrive
    // together over two seconds rather than the sound landing first.
    rampVol(S.running ? S.volume : 0, firstStart ? 2.0 : 0.35,
            firstStart ? audioCtx.currentTime + lead : undefined);
  });
}

// Deliberately keeps the context and the worklet alive. Closing and rebuilding
// them on every toggle reintroduces exactly the device-engagement click this
// is here to avoid.
export function audioOff() {
  S.audioEnabled = false;
  if (!audioCtx) return;
  applyAudioShape();
  closeAt = 0;   // muting the layer shuts the tails too, as it always has
  rampVol(0, 0.25);
  followBackground();
}

// spacebar pauses the whole experience, sound included
let hasRisen = false;
export function applyAudioGain() {
  // If audio has somehow never started, start it here rather than going quiet.
  // This is the only place that knows the session is actually running, so it is
  // the right place to be self-healing about it.
  if (!audioHasPlayed) {
    followBackground();
    if (S.running && audioLayerChecked()) audioOn();
    return;
  }
  // The very first time the volume actually comes up it takes the same two
  // seconds the field does. After that the space bar is an instant stop and
  // start, which is what a pause should feel like.
  //
  // A pause is instant for the sources only. The gates below take every
  // voice out, dry and send alike, over the same 0.12 s the master used to
  // take, and the master stays open while the rooms ring out, then closes.
  // A pause is told apart from a volume move while paused by the gates
  // still being open: only the first starts a new tail.
  const pausing = !S.running && srcOpen;
  setSources(S.running);
  if (S.running) {
    closeAt = 0;
    const dur = hasRisen ? 0.12 : 2.0;
    hasRisen = true;
    rampVol(S.volume, dur);
    followBackground();
    return;
  }
  const g = volGain.gain, now = audioCtx.currentTime;
  if (pausing) {
    closeAt = now + tailSeconds();
    // A pause in the middle of the very first fade in holds the level the
    // fade had reached rather than jumping the tail up to full volume.
    holdMaster(Math.min(S.volume, g.value), closeAt);
  } else if (closeAt > now + SRC_GATE_S) {
    holdMaster(S.volume, closeAt);   // the volume moved under a ringing tail
  } else {
    closeAt = 0;
    rampVol(0, SRC_GATE_S);
  }
  followBackground();
}

// The lock screen's silent loop (js/background.js) plays while anything can
// be heard: the transport running with the sound on, and after a pause for
// as long as the master stays open on the rooms' tails. Then it pauses, and
// a paused session lets the phone sleep. On an iPhone without
// navigator.audioSession the loop is what keeps the ring switch from
// silencing the sound, so it must never stop while something still plays.
// Media Session's play and pause follow the transport alone.
function followBackground() {
  const audible = !!(S.running && S.audioEnabled);
  const ringS = !audible && closeAt > 0 && audioCtx
    ? closeAt + TAIL_CLOSE_S - audioCtx.currentTime : 0;
  setBackgroundPlaying(!!S.running, audible, ringS);
}

// ---------- the pause gate ----------
// One gain on every path a sound source takes into the mix: the worklet's
// three outputs (above), and the piano's, the clouds' and the atmosphere's
// dry buses and room inputs (each registers its own). Each sits upstream of
// every room, so closing them stops anything new reaching a reverb while
// the reverb itself keeps ringing into an open master. They belong to the
// pause alone: levels, mutes and solos all live on their own gains, so a
// gate multiplies whatever those are doing and never has to know.
const SRC_GATE_S = 0.12;
const srcGates = [];
let srcOpen = true;
// Registered at build time, starting at whatever the transport says now, so
// a bus built while paused comes up closed and opens with the next resume.
export function sourceGate(prm) {
  prm.value = srcOpen ? 1 : 0;
  srcGates.push(prm);
}
function setSources(open) {
  if (open === srcOpen || !audioCtx) return;
  srcOpen = open;
  const now = audioCtx.currentTime;
  for (let i = 0; i < srcGates.length; i++) {
    anchorParam(srcGates[i], now);
    srcGates[i].linearRampToValueAtTime(open ? 1 : 0, now + SRC_GATE_S);
  }
}

// How long the master waits after a pause. Every room here is a noise burst
// shaped by (1 - t / length) to a power (fillIR), so it is exactly its
// length long and then silent: nothing rings past the longest impulse in
// play. That is the harmonics' fixed room, the live pip shape's room, the
// piano's (the clouds' too, shared or, on a Heart island, copied: js/clouds.js)
// and the atmosphere's rooms at their current decay settings, and each sequencer line's own room (js/piano.js lineRoom), all
// counted whether or not they are sounding, since holding a silent master
// open a few seconds longer costs nothing. On top
// of that: the gates' own ramp, the last sound fed in on its way down, and
// a little over for the audio clock running ahead of the page. Then a short
// fade, so the close lands on a tail already near nothing and never clicks.
// (The pause used to land on the master directly, which cut every tail.)
const HARM_IR_S = 2.6;
const TAIL_MARGIN_S = 0.25;
const TAIL_CLOSE_S = 0.3;
let closeAt = 0;   // audio clock time the master starts closing; 0 when none is pending
function tailSeconds() {
  const n = x => (typeof x === 'number' && x > 0) ? x : 0;
  let t = Math.max(HARM_IR_S, n(pipRevTime()), n(S.pianoRevTime), n(S.ambRevTime));
  const qs = S.seqs;
  if (qs) for (let i = 0; i < qs.length; i++) if (qs[i]) t = Math.max(t, Math.min(15, n(qs[i].revTime)));
  return t + SRC_GATE_S + TAIL_MARGIN_S;
}
// Holds the master at level until `until`, then closes it. Written straight
// onto the parameter as rampVol writes outside a transition, and forgotten
// as a transition's target the same way, so a resume's rampVol simply
// cancels the close and ramps up from wherever the master is.
function holdMaster(level, until) {
  const g = volGain.gain, now = audioCtx.currentTime;
  glideTarget.delete(g);
  anchorParam(g, now);
  g.linearRampToValueAtTime(level, now + SRC_GATE_S);
  g.setValueAtTime(level, until);
  g.linearRampToValueAtTime(0, until + TAIL_CLOSE_S);
  masterTo(0, until + TAIL_CLOSE_S);
}

// ---------- Heart's rest ----------
// While the master is shut nothing Heart renders can be heard, and paused
// that lasts as long as the pause does, yet its stages would go on
// rendering the gated silence the whole time. So once the master has
// closed (a pause's tails rung out, holdMaster; or any ramp to nothing) and
// no hand has moved for REST_QUIET_MS, Heart rests (js/heart/engine.js):
// the drain stops consuming and every render worker sleeps. Anything that
// opens the master wakes it, and so does any sign of a hand (heartNudge,
// from the page's input), which is the one that matters: a pointer moving
// towards the field wakes it some way ahead of the click that resumes, and
// the cushion has refilled long before the gates open. A wake that is the
// resume itself (a tap on a phone) loses the first ~43 ms of the 0.12 s
// fade in to the refill. The time map never moves either way.
const REST_QUIET_MS = 2000;
let quietAt = Infinity;   // audio clock time from which the master holds at 0; Infinity while it opens
let restTimer = 0, lastNudge = -Infinity;
function masterTo(level, at) {
  if (level > 0) {
    quietAt = Infinity;
    const eng = heartEngine();
    if (eng && eng.isResting()) {
      eng.wake();
      if (IDLE_DIAG) console.log('[idlediag] Heart wakes: the master opens');
    }
    return;
  }
  quietAt = at;
  armRest();
}
function armRest() {
  if (restTimer || quietAt === Infinity || !audioCtx) return;
  const eng = heartEngine();
  if (!eng || eng.isResting()) return;
  const wait = Math.max(0, (quietAt - audioCtx.currentTime) * 1000, REST_QUIET_MS - (performance.now() - lastNudge));
  restTimer = after(Math.ceil(wait) + 50, restCheck);
}
function restCheck() {
  restTimer = 0;
  const eng = heartEngine();
  // a context not running renders nothing to rest from; the next master
  // move or hand arms the check again
  if (!eng || eng.isResting() || quietAt === Infinity || !audioCtx || audioCtx.state !== 'running') return;
  if (audioCtx.currentTime >= quietAt && performance.now() - lastNudge >= REST_QUIET_MS) {
    eng.rest();
    if (IDLE_DIAG) console.log('[idlediag] Heart rests: the master is shut and no hand has moved for ' + (REST_QUIET_MS / 1000) + ' s');
    return;
  }
  armRest();
}
// Any input, as it happens (main.js; the worker shell's page, in worker
// mode): a resting Heart wakes, and rests again once the hand has been
// still for REST_QUIET_MS with the master still shut. A pointer move costs
// a clock read and a store.
export function heartNudge() {
  lastNudge = performance.now();
  const eng = heartEngine();
  if (eng && eng.isResting()) {
    eng.wake();
    if (IDLE_DIAG) console.log('[idlediag] Heart wakes: a hand');
  }
  armRest();
}
// The idle diagnostic's reading (main.js): whether Heart rests, and every
// frame its stages have rendered or skipped, summed; null without Heart.
export function heartRestInfo() {
  const eng = heartEngine();
  return eng ? { resting: eng.isResting(), heads: eng.heads() } : null;
}
