// The word layer: single words flashed one at a time onto the dark field.
//
// This is not vocabulary, it is ballast. The strobe and the drone do the work of
// loosening attention; a word arriving in that state is read by the body before
// it is read by the mind, so the whole list leans concrete and sensory. "grass"
// lands somewhere. "potential" does not. When a word had an abstract twin, the
// plain one won.
//
// SAFETY RULE, and it is absolute. These are read with the guard down, often
// mid-session, often with something tender already open. Every word here has to
// be survivable in that state. So: nothing about harm, illness, injury, danger
// or fear; nothing about loss, absence or being left; no family-role nouns, which
// land differently for everyone and never neutrally; nothing about bodies as
// objects to be judged; no sex, no doctrine, no clinical or therapy vocabulary,
// and nothing that asks for effort, improvement or worth.
//
// The subtler half of the rule: a word is out if its shadow is what gives it
// meaning. "safe" is in. "unafraid" is out, because it has to name the fear to
// mean anything, and naming it is exactly what a flashed word does. Same reason
// "whole" stays and "intact" goes. When it was close, it was cut -- the list is
// long enough that nothing borderline is load-bearing.
//
// Themes exist so a session can be steered (all water, all creatures) or left
// wide open. Most words carry one or two. Tagging is honest: a word is only
// tagged `open` if it actually opens something, not to pad the theme.

export const THEMES = {
  body:       'body',
  breath:     'breath',
  movement:   'movement',
  nature:     'nature',
  water:      'water',
  sky:        'sky',
  light:      'light',
  creatures:  'creatures',
  play:       'play',
  joy:        'joy',
  calm:       'calm',
  safety:     'safety',
  trust:      'trust',
  open:       'openness',
  connection: 'connection',
  wonder:     'wonder',
  abundance:  'abundance',
  time:       'timelessness',
  texture:    'texture',
  art:        'color and music',
  space:      'outer space',
  shape:      'shape and form'
};

// Every entry is [word, ...themes]. Grouped by where each word came from rather
// than alphabetically, because reading a group top to bottom is how you notice a
// word that does not belong in it.
export const WORDS = [

  // ---------- body ----------
  // Front-loaded deliberately. Naming a part is the fastest way down out of the
  // head, and it works even when nothing else is landing.
  ['body', 'body'],
  ['head', 'body'],
  ['face', 'body'],
  ['cheek', 'body'],
  ['cheeks', 'body'],
  ['chin', 'body'],
  ['forehead', 'body'],
  ['brow', 'body'],
  ['eyebrow', 'body'],
  ['eyelash', 'body'],
  ['eyelashes', 'body'],
  ['eye', 'body'],
  ['eyes', 'body'],
  ['eyelid', 'body'],
  ['nose', 'body'],
  ['mouth', 'body'],
  ['lips', 'body'],
  ['ear', 'body'],
  ['ears', 'body'],
  ['earlobe', 'body'],
  ['jaw', 'body'],
  ['neck', 'body'],
  ['shoulder', 'body'],
  ['shoulders', 'body'],
  ['collarbone', 'body'],
  ['arm', 'body'],
  ['arms', 'body'],
  ['forearm', 'body'],
  ['elbow', 'body'],
  ['wrist', 'body'],
  ['wrists', 'body'],
  ['hand', 'body'],
  ['hands', 'body'],
  ['palm', 'body'],
  ['palms', 'body'],
  ['finger', 'body'],
  ['fingers', 'body'],
  ['fingertip', 'body'],
  ['fingertips', 'body'],
  ['thumb', 'body'],
  ['knuckle', 'body'],
  ['knuckles', 'body'],
  ['chest', 'body'],
  ['ribs', 'body'],
  ['heart', 'body', 'connection'],
  ['heartbeat', 'body'],
  ['pulse', 'body'],
  ['belly', 'body'],
  ['navel', 'body'],
  ['back', 'body'],
  ['spine', 'body'],
  ['hip', 'body'],
  ['hips', 'body'],
  ['leg', 'body'],
  ['legs', 'body'],
  ['knee', 'body'],
  ['knees', 'body'],
  ['shin', 'body'],
  ['ankle', 'body'],
  ['ankles', 'body'],
  ['foot', 'body'],
  ['feet', 'body'],
  ['heel', 'body'],
  ['heels', 'body'],
  ['sole', 'body'],
  ['soles', 'body'],
  ['toe', 'body'],
  ['toes', 'body'],
  ['skin', 'body', 'texture'],
  ['torso', 'body'],
  ['limbs', 'body'],
  ['blink', 'body'],
  ['gaze', 'body'],
  ['glance', 'body'],
  ['sight', 'body'],
  ['scent', 'body', 'nature'],
  ['fragrance', 'body', 'nature'],
  ['taste', 'body'],
  ['senses', 'body'],
  ['sense', 'body'],
  ['sensation', 'body'],
  ['sensations', 'body'],
  ['feeling', 'body'],
  ['blinking', 'body'],
  ['tingle', 'body'],
  ['tingling', 'body'],
  ['balance', 'body', 'calm'],
  ['within', 'body', 'open'],
  ['inside', 'body'],
  ['center', 'body', 'calm'],
  ['powerful', 'body', 'open'],
  ['power', 'body', 'open'],
  ['alive', 'body', 'wonder'],
  ['aliveness', 'body', 'wonder'],

  // ---------- breath ----------
  ['breath', 'breath'],
  ['breathe', 'breath'],
  ['breathing', 'breath'],
  ['inhale', 'breath'],
  ['exhale', 'breath'],
  ['lungs', 'breath', 'body'],
  ['sigh', 'breath', 'calm'],
  ['air', 'breath', 'sky'],
  ['airy', 'breath', 'open'],
  ['deepening', 'breath'],
  ['filling', 'breath', 'abundance'],
  ['rising', 'breath', 'movement'],
  ['steady', 'breath', 'safety'],
  ['slow', 'breath', 'calm'],
  ['easy', 'breath', 'calm'],
  ['ease', 'breath', 'calm'],
  ['effortless', 'breath', 'calm'],
  ['flowing', 'breath', 'water'],
  ['flow', 'breath', 'water'],

  // ---------- movement ----------
  ['walk', 'movement'],
  ['walking', 'movement'],
  ['step', 'movement'],
  ['steps', 'movement'],
  ['stride', 'movement'],
  ['stroll', 'movement'],
  ['strolling', 'movement'],
  ['amble', 'movement'],
  ['saunter', 'movement'],
  ['meander', 'movement'],
  ['wander', 'movement', 'open'],
  ['wandering', 'movement', 'open'],
  ['roam', 'movement', 'open'],
  ['roaming', 'movement', 'open'],
  ['run', 'movement'],
  ['running', 'movement'],
  ['dash', 'movement', 'play'],
  ['dart', 'movement'],
  ['skip', 'movement', 'play'],
  ['skipping', 'movement', 'play'],
  ['hop', 'movement', 'play'],
  ['hopping', 'movement', 'play'],
  ['jump', 'movement', 'play'],
  ['jumping', 'movement', 'play'],
  ['leap', 'movement', 'play'],
  ['leaping', 'movement', 'play'],
  ['bound', 'movement', 'play'],
  ['bounding', 'movement', 'play'],
  ['bounce', 'movement', 'play'],
  ['bouncing', 'movement', 'play'],
  ['spin', 'movement', 'play'],
  ['spinning', 'movement', 'play'],
  ['twirl', 'movement', 'play'],
  ['twirling', 'movement', 'play'],
  ['swirl', 'movement'],
  ['swirling', 'movement'],
  ['whirl', 'movement'],
  ['spiral', 'shape', 'movement', 'wonder', 'space'],
  ['circle', 'shape', 'movement', 'connection'],

  // ---- shape and form ----------------------------------------------------
  // Plain geometry. Nothing in the other themes covers it, and a shape is
  // about as far from a narrating mind as a word can get.
  ['triangle', 'shape'],
  ['square', 'shape'],
  ['rectangle', 'shape'],
  ['cube', 'shape'],
  ['sphere', 'shape'],
  ['torus', 'shape'],
  ['circling', 'movement'],
  ['turn', 'movement'],
  ['turning', 'movement'],
  ['sway', 'movement', 'calm'],
  ['swaying', 'movement', 'calm'],
  ['rocking', 'movement', 'calm'],
  ['roll', 'movement', 'play'],
  ['rolling', 'movement', 'play'],
  ['glide', 'movement'],
  ['gliding', 'movement'],
  ['slide', 'movement', 'play'],
  ['sliding', 'movement', 'play'],
  ['drift', 'movement', 'calm'],
  ['drifting', 'movement', 'calm'],
  ['float', 'movement', 'water'],
  ['floating', 'movement', 'water'],
  ['soar', 'movement', 'sky'],
  ['soaring', 'movement', 'sky'],
  ['fly', 'movement', 'sky'],
  ['flying', 'movement', 'sky'],
  ['flutter', 'movement', 'creatures'],
  ['fluttering', 'movement', 'creatures'],
  ['swoop', 'movement', 'sky'],
  ['dance', 'movement', 'joy'],
  ['dancing', 'movement', 'joy'],
  ['waltz', 'movement', 'art'],
  ['sashay', 'movement', 'play'],
  ['frolic', 'movement', 'play'],
  ['romp', 'movement', 'play'],
  ['prance', 'movement', 'play'],
  ['scamper', 'movement', 'creatures'],
  ['wiggle', 'movement', 'play'],
  ['shimmy', 'movement', 'play'],
  ['stretch', 'movement', 'body'],
  ['stretching', 'movement', 'body'],
  ['sit', 'movement', 'calm'],
  ['sitting', 'movement', 'calm'],
  ['stand', 'movement'],
  ['standing', 'movement'],
  ['rest', 'movement', 'calm'],
  ['resting', 'movement', 'calm'],
  ['swim', 'movement', 'water'],
  ['swimming', 'movement', 'water'],
  ['wade', 'movement', 'water'],
  ['wading', 'movement', 'water'],
  ['ride', 'movement', 'play'],
  ['riding', 'movement', 'play'],
  ['cartwheel', 'movement', 'play'],
  ['somersault', 'movement', 'play'],
  ['handstand', 'movement', 'play'],

  // ---------- nature ----------
  ['grass', 'nature'],
  ['meadow', 'nature'],
  ['field', 'nature'],
  ['pasture', 'nature'],
  ['prairie', 'nature'],
  ['moss', 'nature', 'texture'],
  ['mossy', 'nature', 'texture'],
  ['fern', 'nature'],
  ['leaf', 'nature'],
  ['leaves', 'nature'],
  ['leafy', 'nature', 'texture'],
  ['tree', 'nature'],
  ['trees', 'nature'],
  ['oak', 'nature'],
  ['willow', 'nature'],
  ['birch', 'nature'],
  ['pine', 'nature'],
  ['cedar', 'nature'],
  ['maple', 'nature'],
  ['aspen', 'nature'],
  ['redwood', 'nature'],
  ['evergreen', 'nature', 'time'],
  ['branch', 'nature'],
  ['branches', 'nature'],
  ['bough', 'nature'],
  ['twig', 'nature'],
  ['bark', 'nature', 'texture'],
  ['sap', 'nature'],
  ['root', 'nature', 'safety'],
  ['roots', 'nature', 'safety'],
  ['seed', 'nature', 'wonder'],
  ['seeds', 'nature', 'wonder'],
  ['seedling', 'nature', 'wonder'],
  ['sprout', 'nature', 'wonder'],
  ['bud', 'nature'],
  ['buds', 'nature'],
  ['blossom', 'nature', 'open'],
  ['bloom', 'nature', 'open'],
  ['blooming', 'nature', 'open'],
  ['blossoming', 'nature', 'open'],
  ['flower', 'nature'],
  ['flowers', 'nature'],
  ['petal', 'nature', 'texture'],
  ['petals', 'nature', 'texture'],
  ['rose', 'nature'],
  ['roses', 'nature'],
  ['daisy', 'nature'],
  ['daisies', 'nature'],
  ['lily', 'nature'],
  ['lilac', 'nature', 'art'],
  ['jasmine', 'nature'],
  ['lavender', 'nature', 'art'],
  ['sunflower', 'nature'],
  ['poppy', 'nature'],
  ['tulip', 'nature'],
  ['clover', 'nature'],
  ['dandelion', 'nature'],
  ['honeysuckle', 'nature'],
  ['heather', 'nature'],
  ['bluebell', 'nature'],
  ['primrose', 'nature'],
  ['marigold', 'nature'],
  ['garden', 'nature', 'safety'],
  ['vineyard', 'nature', 'abundance'],
  ['grove', 'nature'],
  ['forest', 'nature'],
  ['woodland', 'nature'],
  ['glade', 'nature'],
  ['clearing', 'nature', 'open'],
  ['hedgerow', 'nature'],
  ['hill', 'nature'],
  ['hills', 'nature'],
  ['hillside', 'nature'],
  ['valley', 'nature'],
  ['mountain', 'nature'],
  ['mountains', 'nature'],
  ['ridge', 'nature'],
  ['canyon', 'nature'],
  ['dune', 'nature'],
  ['dunes', 'nature'],
  ['path', 'nature'],
  ['pathway', 'nature'],
  ['trail', 'nature'],
  ['stone', 'nature'],
  ['stones', 'nature'],
  ['pebble', 'nature', 'texture'],
  ['pebbles', 'nature', 'texture'],
  ['boulder', 'nature'],
  ['rock', 'nature'],
  ['sand', 'nature', 'texture'],
  ['sandy', 'nature', 'texture'],
  ['soil', 'nature'],
  ['earth', 'nature', 'safety', 'space'],
  ['ground', 'nature', 'safety'],
  ['grounded', 'safety', 'body'],
  ['grounding', 'safety', 'body'],
  ['clay', 'nature', 'art'],
  ['mud', 'nature', 'play'],
  ['pollen', 'nature'],
  ['nectar', 'nature', 'abundance'],
  ['honey', 'nature', 'abundance'],
  ['honeycomb', 'nature', 'texture'],
  ['berry', 'nature'],
  ['berries', 'nature'],
  ['apple', 'nature'],
  ['apples', 'nature'],
  ['peach', 'nature', 'art'],
  ['pear', 'nature'],
  ['plum', 'nature', 'art'],
  ['cherry', 'nature'],
  ['cherries', 'nature'],
  ['apricot', 'nature'],
  ['lemon', 'nature', 'art'],
  ['melon', 'nature'],
  ['fig', 'nature'],
  ['grape', 'nature'],
  ['grapes', 'nature'],
  ['acorn', 'nature'],
  ['pinecone', 'nature'],
  ['mushroom', 'nature'],
  ['lichen', 'nature', 'texture'],
  ['vine', 'nature'],
  ['ivy', 'nature'],
  ['reed', 'nature', 'water'],
  ['reeds', 'nature', 'water'],
  ['cattail', 'nature', 'water'],
  ['wheat', 'nature', 'abundance'],
  ['barley', 'nature', 'abundance'],
  ['sage', 'nature', 'art'],
  ['mint', 'nature'],
  ['thyme', 'nature'],
  ['basil', 'nature'],
  ['rosemary', 'nature'],
  ['cinnamon', 'nature'],
  ['vanilla', 'nature'],
  ['spring', 'nature', 'water'],
  ['summer', 'nature', 'time'],
  ['autumn', 'nature', 'time'],
  ['meadowlark', 'nature', 'creatures'],
  ['wilderness', 'nature', 'open'],
  ['wild', 'nature', 'open'],
  ['wildflower', 'nature'],
  ['wildflowers', 'nature'],

  // ---------- water ----------
  ['water', 'water'],
  ['ocean', 'water'],
  ['sea', 'water'],
  ['wave', 'water'],
  ['waves', 'water'],
  ['tide', 'water', 'time'],
  ['tides', 'water', 'time'],
  ['surf', 'water'],
  ['foam', 'water', 'texture'],
  ['spray', 'water'],
  ['mist', 'water'],
  ['misty', 'water'],
  ['current', 'water'],
  ['river', 'water'],
  ['stream', 'water'],
  ['brook', 'water'],
  ['creek', 'water'],
  ['waterfall', 'water'],
  ['cascade', 'water'],
  ['pool', 'water'],
  ['pond', 'water'],
  ['lake', 'water'],
  ['lagoon', 'water'],
  ['bay', 'water'],
  ['cove', 'water', 'safety'],
  ['inlet', 'water'],
  ['estuary', 'water'],
  ['shore', 'water'],
  ['shoreline', 'water'],
  ['beach', 'water'],
  ['sandbar', 'water'],
  ['harbor', 'water', 'safety'],
  ['island', 'water'],
  ['reef', 'water'],
  ['seaweed', 'water'],
  ['kelp', 'water'],
  ['seashell', 'water'],
  ['driftwood', 'water', 'texture'],
  ['ripple', 'water'],
  ['ripples', 'water'],
  ['rippling', 'water'],
  ['splash', 'water', 'play'],
  ['splashing', 'water', 'play'],
  ['droplet', 'water'],
  ['droplets', 'water'],
  ['dew', 'water', 'nature'],
  ['dewy', 'water', 'texture'],
  ['rain', 'water'],
  ['raindrop', 'water'],
  ['raindrops', 'water'],
  ['rainfall', 'water'],
  ['shower', 'water'],
  ['puddle', 'water', 'play'],
  ['bubble', 'water', 'play'],
  ['bubbles', 'water', 'play'],
  ['fizz', 'water', 'play'],
  ['boat', 'water', 'play'],
  ['canoe', 'water', 'play'],
  ['kayak', 'water', 'play'],
  ['raft', 'water', 'play'],
  ['sail', 'water'],
  ['sailing', 'water'],
  ['oar', 'water'],
  ['paddle', 'water', 'play'],
  ['buoy', 'water'],
  ['lighthouse', 'water', 'safety'],
  ['fountain', 'water'],
  ['shallows', 'water'],
  ['tidepool', 'water', 'wonder'],
  ['swell', 'water'],
  ['lapping', 'water', 'calm'],
  ['glassy', 'water', 'calm'],

  // ---------- sky ----------
  ['sky', 'sky', 'open'],
  ['skies', 'sky', 'open'],
  ['cloud', 'sky'],
  ['clouds', 'sky'],
  ['sunrise', 'sky', 'wonder'],
  ['sunset', 'sky', 'wonder'],
  ['dawn', 'sky', 'time'],
  ['dusk', 'sky', 'time'],
  ['twilight', 'sky', 'time'],
  ['daybreak', 'sky', 'time'],
  ['noon', 'sky', 'time'],
  ['horizon', 'sky', 'open'],
  ['sun', 'sky', 'light'],
  ['sunshine', 'sky', 'light'],
  ['sunlight', 'sky', 'light'],
  ['sunbeam', 'sky', 'light'],
  ['sunlit', 'sky', 'light'],
  ['moon', 'sky', 'wonder', 'space'],
  ['moonlight', 'sky', 'light'],
  ['moonbeam', 'sky', 'light'],
  ['moonrise', 'sky', 'wonder'],
  ['star', 'sky', 'wonder'],
  ['stars', 'sky', 'wonder'],
  ['starlight', 'sky', 'light', 'space'],
  ['starry', 'sky', 'wonder'],
  ['constellation', 'sky', 'wonder', 'space'],
  ['comet', 'sky', 'wonder', 'space'],
  ['galaxy', 'sky', 'wonder', 'space'],
  ['nebula', 'sky', 'wonder', 'space'],
  ['aurora', 'sky', 'wonder'],
  ['planet', 'sky', 'wonder', 'space'],
  ['orbit', 'sky', 'time', 'space'],
  ['breeze', 'sky', 'calm'],
  ['breezy', 'sky', 'calm'],
  ['wind', 'sky'],
  ['gust', 'sky'],
  ['rainbow', 'sky', 'art'],
  ['kite', 'sky', 'play'],
  ['balloon', 'sky', 'play'],
  ['balloons', 'sky', 'play'],
  ['feather', 'sky', 'texture'],
  ['feathers', 'sky', 'texture'],
  ['wing', 'sky', 'creatures'],
  ['wings', 'sky', 'creatures'],
  ['flight', 'sky'],
  ['glider', 'sky', 'play'],
  ['updraft', 'sky'],
  ['vapor', 'sky'],
  ['overhead', 'sky', 'open'],
  ['above', 'sky', 'open'],
  ['skyward', 'sky', 'open'],

  // ---------- light ----------
  ['light', 'light'],
  ['glow', 'light'],
  ['glowing', 'light'],
  ['aglow', 'light'],
  ['shine', 'light'],
  ['shining', 'light'],
  ['shimmer', 'light'],
  ['shimmering', 'light'],
  ['gleam', 'light'],
  ['gleaming', 'light'],
  ['glimmer', 'light'],
  ['sparkle', 'light', 'joy'],
  ['sparkling', 'light', 'joy'],
  ['twinkle', 'light', 'joy'],
  ['glitter', 'light', 'play'],
  ['glisten', 'light'],
  ['glistening', 'light'],
  ['radiant', 'light', 'joy'],
  ['radiance', 'light', 'joy'],
  ['luminous', 'light'],
  ['bright', 'light', 'joy'],
  ['brightness', 'light'],
  ['beam', 'light'],
  ['beams', 'light'],
  ['ray', 'light'],
  ['rays', 'light'],
  ['dapple', 'light', 'nature'],
  ['dappled', 'light', 'nature'],
  ['sheen', 'light', 'texture'],
  ['flicker', 'light'],
  ['prism', 'light', 'art'],
  ['candle', 'light', 'safety'],
  ['candlelight', 'light', 'safety'],
  ['lantern', 'light', 'safety'],
  ['lamp', 'light', 'safety'],
  ['lamplight', 'light', 'safety'],
  ['glowworm', 'light', 'creatures'],
  ['lightness', 'light', 'joy'],
  ['clear', 'light', 'trust'],
  ['clarity', 'light', 'trust'],
  ['golden', 'light', 'art'],
  ['gold', 'light', 'art'],
  ['amber', 'light', 'art'],
  ['daylight', 'light', 'sky'],
  ['iridescent', 'light', 'wonder'],
  ['opaline', 'light', 'wonder'],
  ['lucid', 'light', 'wonder'],
  ['lucid dream', 'wonder', 'calm'],

  // ---------- creatures ----------
  ['bird', 'creatures'],
  ['birds', 'creatures'],
  ['birdsong', 'creatures', 'art'],
  ['songbird', 'creatures'],
  ['robin', 'creatures'],
  ['sparrow', 'creatures'],
  ['swallow', 'creatures'],
  ['wren', 'creatures'],
  ['finch', 'creatures'],
  ['lark', 'creatures'],
  ['dove', 'creatures', 'calm'],
  ['heron', 'creatures'],
  ['crane', 'creatures'],
  ['swan', 'creatures'],
  ['duck', 'creatures'],
  ['duckling', 'creatures'],
  ['goose', 'creatures'],
  ['gosling', 'creatures'],
  ['owl', 'creatures'],
  ['hummingbird', 'creatures'],
  ['kingfisher', 'creatures'],
  ['pelican', 'creatures'],
  ['gull', 'creatures'],
  ['butterfly', 'creatures', 'wonder'],
  ['butterflies', 'creatures', 'wonder'],
  ['moth', 'creatures'],
  ['bee', 'creatures'],
  ['bees', 'creatures'],
  ['bumblebee', 'creatures'],
  ['ladybug', 'creatures'],
  ['dragonfly', 'creatures'],
  ['firefly', 'creatures', 'light'],
  ['fireflies', 'creatures', 'light'],
  ['cricket', 'creatures'],
  ['crickets', 'creatures'],
  ['grasshopper', 'creatures'],
  ['snail', 'creatures'],
  ['turtle', 'creatures'],
  ['tortoise', 'creatures'],
  ['frog', 'creatures'],
  ['tadpole', 'creatures'],
  ['fish', 'creatures', 'water'],
  ['minnow', 'creatures', 'water'],
  ['dolphin', 'creatures', 'water'],
  ['dolphins', 'creatures', 'water'],
  ['whale', 'creatures', 'water'],
  ['seal', 'creatures', 'water'],
  ['otter', 'creatures', 'water'],
  ['manatee', 'creatures', 'water'],
  ['starfish', 'creatures', 'water'],
  ['crab', 'creatures', 'water'],
  ['seahorse', 'creatures', 'water'],
  ['deer', 'creatures'],
  ['fawn', 'creatures'],
  ['rabbit', 'creatures'],
  ['bunny', 'creatures'],
  ['hare', 'creatures'],
  ['squirrel', 'creatures'],
  ['chipmunk', 'creatures'],
  ['hedgehog', 'creatures'],
  ['fox', 'creatures'],
  ['mouse', 'creatures'],
  ['horse', 'creatures'],
  ['pony', 'creatures'],
  ['lamb', 'creatures'],
  ['sheep', 'creatures'],
  ['goat', 'creatures'],
  ['cow', 'creatures'],
  ['dog', 'creatures'],
  ['puppy', 'creatures'],
  ['cat', 'creatures'],
  ['kitten', 'creatures'],
  ['kitty', 'creatures'],
  ['whiskers', 'creatures', 'texture'],
  ['paw', 'creatures'],
  ['paws', 'creatures'],
  ['purr', 'creatures', 'calm'],
  ['purring', 'creatures', 'calm'],
  ['tail', 'creatures'],
  ['nest', 'creatures', 'safety'],
  ['burrow', 'creatures', 'safety'],
  ['den', 'creatures', 'safety'],
  ['hive', 'creatures', 'abundance'],
  ['pod', 'creatures'],
  ['flock', 'creatures', 'connection'],
  ['herd', 'creatures', 'connection'],
  ['panda', 'creatures'],
  ['koala', 'creatures'],
  ['sloth', 'creatures', 'calm'],
  ['alpaca', 'creatures'],
  ['llama', 'creatures'],
  ['penguin', 'creatures'],

  // ---------- play ----------
  ['play', 'play'],
  ['playing', 'play'],
  ['playful', 'play', 'joy'],
  ['playfulness', 'play', 'joy'],
  ['game', 'play'],
  ['games', 'play'],
  ['ball', 'play'],
  ['swing', 'play', 'movement'],
  ['swinging', 'play', 'movement'],
  ['swings', 'play'],
  ['seesaw', 'play'],
  ['sandbox', 'play'],
  ['sandcastle', 'play'],
  ['marbles', 'play'],
  ['hopscotch', 'play'],
  ['giggle', 'play', 'joy'],
  ['giggles', 'play', 'joy'],
  ['giggling', 'play', 'joy'],
  ['tickle', 'play', 'joy'],
  ['toy', 'play'],
  ['toys', 'play'],
  ['teddy', 'play', 'safety'],
  ['yoyo', 'play'],
  ['puzzle', 'play'],
  ['crayon', 'play', 'art'],
  ['crayons', 'play', 'art'],
  ['chalk', 'play', 'art'],
  ['sticker', 'play'],
  ['stickers', 'play'],
  ['confetti', 'play', 'joy'],
  ['carousel', 'play', 'wonder'],
  ['parade', 'play', 'joy'],
  ['picnic', 'play', 'connection'],
  ['trampoline', 'play'],
  ['pinwheel', 'play'],
  ['tricycle', 'play'],
  ['scooter', 'play'],
  ['wagon', 'play'],
  ['sled', 'play'],
  ['bicycle', 'play'],
  ['bike', 'play'],
  ['car', 'play'],
  ['train', 'play'],
  ['puppet', 'play'],
  ['kaleidoscope', 'play', 'wonder'],
  ['whistle', 'play', 'art'],
  ['fun', 'play', 'joy'],
  ['silly', 'play', 'joy'],
  ['whimsy', 'play', 'wonder'],
  ['whimsical', 'play', 'wonder'],
  ['recess', 'play'],
  ['playground', 'play'],

  // ---------- joy ----------
  ['joy', 'joy'],
  ['joyful', 'joy'],
  ['happy', 'joy'],
  ['happiness', 'joy'],
  ['smile', 'joy', 'body'],
  ['smiles', 'joy'],
  ['smiling', 'joy', 'body'],
  ['grin', 'joy', 'body'],
  ['grinning', 'joy'],
  ['laugh', 'joy'],
  ['laughs', 'joy'],
  ['laughter', 'joy'],
  ['laughing', 'joy'],
  ['chuckle', 'joy'],
  ['delight', 'joy'],
  ['delighted', 'joy'],
  ['delightful', 'joy'],
  ['glee', 'joy'],
  ['gleeful', 'joy'],
  ['cheer', 'joy'],
  ['cheerful', 'joy'],
  ['merry', 'joy'],
  ['sunny', 'joy', 'sky'],
  ['bliss', 'joy'],
  ['blissful', 'joy'],
  ['buoyant', 'joy'],
  ['lighthearted', 'joy'],
  ['glad', 'joy'],
  ['gladness', 'joy'],
  ['sweet', 'joy'],
  ['sweetness', 'joy'],
  ['yes', 'joy', 'open'],
  ['celebration', 'joy', 'connection'],
  ['celebrate', 'joy', 'connection'],
  ['festive', 'joy'],
  ['gratitude', 'joy', 'abundance'],
  ['grateful', 'joy', 'abundance'],
  ['thankful', 'joy'],
  ['thankfulness', 'joy', 'abundance'],
  ['thanks', 'joy'],
  ['wonderful', 'joy', 'wonder'],
  ['lovely', 'joy'],
  ['dear', 'joy', 'connection'],
  ['beaming', 'joy', 'light'],
  ['humming', 'joy', 'art'],
  ['zest', 'joy'],
  ['brimful', 'joy', 'abundance'],

  // ---------- calm ----------
  ['calm', 'calm'],
  ['calmness', 'calm'],
  ['quiet', 'calm'],
  ['quietness', 'calm'],
  ['still', 'calm'],
  ['stillness', 'calm'],
  ['hush', 'calm'],
  ['hushed', 'calm'],
  ['peace', 'calm'],
  ['peaceful', 'calm'],
  ['serene', 'calm'],
  ['serenity', 'calm'],
  ['tranquil', 'calm'],
  ['tranquility', 'calm'],
  ['gentle', 'calm', 'texture'],
  ['gentleness', 'calm'],
  ['soften', 'calm', 'open'],
  ['softening', 'calm', 'open'],
  ['restful', 'calm'],
  ['lullaby', 'calm', 'art'],
  ['slumber', 'calm'],
  ['dream', 'calm', 'wonder'],
  ['dreams', 'calm', 'wonder'],
  ['dreamy', 'calm', 'wonder'],
  ['blanket', 'calm', 'safety'],
  ['quilt', 'calm', 'texture'],
  ['cozy', 'calm', 'safety'],
  ['snug', 'calm', 'safety'],
  ['hammock', 'calm'],
  ['shade', 'calm', 'nature'],
  ['cool', 'calm'],
  ['mellow', 'calm'],
  ['mild', 'calm'],
  ['silence', 'calm'],
  ['silent', 'calm'],
  ['murmur', 'calm', 'art'],
  ['whisper', 'calm'],
  ['whispering', 'calm'],
  ['melt', 'calm'],
  ['melting', 'calm'],
  ['soothing', 'calm'],
  ['unwinding', 'calm'],
  ['pause', 'calm', 'time'],
  ['patience', 'calm', 'time'],
  ['simple', 'calm'],
  ['simplicity', 'calm'],
  ['smooth', 'calm', 'texture'],
  ['dozing', 'calm'],
  ['nestled', 'calm', 'safety'],

  // ---------- safety ----------
  ['safe', 'safety'],
  ['safety', 'safety'],
  ['shelter', 'safety'],
  ['sheltered', 'safety'],
  ['haven', 'safety'],
  ['home', 'safety'],
  ['hearth', 'safety'],
  ['cocoon', 'safety', 'texture'],
  ['chrysalis', 'safety', 'wonder'],
  ['held', 'safety', 'connection'],
  ['holding', 'safety', 'connection'],
  ['hold', 'safety', 'connection'],
  ['cradle', 'safety'],
  ['cradled', 'safety'],
  ['wrapped', 'safety', 'texture'],
  ['wrap', 'safety', 'texture'],
  ['warm', 'safety', 'texture'],
  ['warmth', 'safety'],
  ['steadiness', 'safety'],
  ['sturdy', 'safety'],
  ['solid', 'safety'],
  ['anchor', 'safety'],
  ['anchored', 'safety'],
  ['stable', 'safety'],
  ['support', 'safety', 'connection'],
  ['supported', 'safety', 'connection'],
  ['tender', 'safety', 'connection'],
  ['tenderness', 'safety', 'connection'],
  ['care', 'safety', 'connection'],
  ['caring', 'safety', 'connection'],
  ['nurture', 'safety', 'connection'],
  ['nurtured', 'safety', 'connection'],
  ['nurturing', 'safety', 'connection'],
  ['protected', 'safety'],
  ['cherished', 'safety', 'connection'],
  ['welcome', 'safety', 'connection'],
  ['welcomed', 'safety', 'connection'],
  ['belong', 'safety', 'connection'],
  ['belonging', 'safety', 'connection'],
  ['window', 'safety'],
  ['windowsill', 'safety'],
  ['doorway', 'safety', 'open'],
  ['porch', 'safety'],
  ['chair', 'safety'],
  ['rug', 'safety', 'texture'],
  ['curtain', 'safety', 'texture'],
  ['bowl', 'safety'],
  ['cup', 'safety'],
  ['mug', 'safety'],
  ['teapot', 'safety'],
  ['kettle', 'safety'],
  ['spoon', 'safety'],
  ['basket', 'safety', 'abundance'],
  ['bread', 'safety', 'abundance'],
  ['tea', 'safety', 'calm'],
  ['cocoa', 'safety', 'calm'],
  ['soup', 'safety'],
  ['book', 'safety'],
  ['page', 'safety'],
  ['pages', 'safety'],
  ['paper', 'safety', 'art'],
  ['baby', 'safety', 'connection'],
  ['child', 'safety', 'connection'],
  ['children', 'safety', 'connection'],
  ['young', 'safety'],
  ['small', 'safety'],
  ['tiny', 'safety'],

  // ---------- trust ----------
  ['trust', 'trust'],
  ['trusting', 'trust'],
  ['trusted', 'trust'],
  ['truth', 'trust'],
  ['true', 'trust'],
  ['honest', 'trust'],
  ['honesty', 'trust'],
  ['real', 'trust'],
  ['genuine', 'trust'],
  ['guided', 'trust'],
  ['guiding', 'trust'],
  ['guide', 'trust'],
  ['willing', 'trust', 'open'],
  ['willingness', 'trust', 'open'],
  ['receptive', 'trust', 'open'],
  ['receiving', 'trust', 'connection'],
  ['receive', 'trust', 'connection'],
  ['whole', 'trust'],
  ['wholeness', 'trust'],
  ['grace', 'trust', 'wonder'],
  ['graceful', 'trust', 'wonder'],
  ['easeful', 'trust', 'calm'],
  ['natural', 'trust', 'nature'],
  ['knowing', 'trust'],
  ['wisdom', 'trust'],
  ['wise', 'trust'],
  ['insight', 'trust', 'wonder'],
  ['spontaneous', 'play', 'open'],
  ['spontaneity', 'play', 'open'],
  ['surefooted', 'trust'],

  // ---------- openness ----------
  ['open', 'open'],
  // Noting practice names the act of attending, which is the technique
  // rather than a slip back into the head.
  ['mindful', 'open', 'calm'],
  ['attention', 'open'],
  ['awareness', 'open'],
  ['notice', 'open'],
  ['noticing', 'open'],
  ['opening', 'open'],
  ['openness', 'open'],
  ['openhearted', 'open', 'connection'],
  ['expansive', 'open'],
  ['expanse', 'open', 'space'],
  ['expand', 'open'],
  ['expanding', 'open'],
  ['wide', 'open'],
  ['widening', 'open'],
  ['vast', 'open', 'wonder'],
  ['vastness', 'open', 'wonder', 'space'],
  ['spacious', 'open'],
  ['spaciousness', 'open'],
  ['space', 'open'],
  ['room', 'open'],
  ['boundless', 'open'],
  ['endless', 'open', 'time'],
  ['infinite', 'open', 'time'],
  ['limitless', 'open'],
  ['free', 'open'],
  ['freedom', 'open'],
  ['freely', 'open'],
  ['unfold', 'open'],
  ['unfolding', 'open'],
  ['unfurl', 'open'],
  ['release', 'open', 'calm'],
  ['releasing', 'open', 'calm'],
  ['letting go', 'open'],
  ['awaken', 'open', 'wonder'],
  ['awakening', 'open', 'wonder'],
  ['unfurling', 'open'],
  ['outward', 'open'],
  ['beyond', 'open', 'wonder'],
  ['broad', 'open'],
  ['sweeping', 'open'],
  ['outdoors', 'open', 'nature'],

  // ---------- connection ----------
  ['together', 'connection'],
  ['togetherness', 'connection'],
  ['connected', 'connection'],
  ['connection', 'connection'],
  ['interconnected', 'connection'],
  ['oneness', 'connection', 'open'],
  ['interwoven', 'connection'],
  ['woven', 'connection', 'texture'],
  ['weave', 'connection', 'texture'],
  ['weaving', 'connection', 'texture'],
  ['tapestry', 'connection', 'art'],
  ['mosaic', 'connection', 'art'],
  ['thread', 'connection', 'texture'],
  ['threads', 'connection', 'texture'],
  ['knit', 'connection', 'texture'],
  ['web', 'connection'],
  ['friend', 'connection'],
  ['friends', 'connection'],
  ['friendship', 'connection'],
  ['companion', 'connection'],
  ['companionship', 'connection'],
  ['neighbor', 'connection'],
  ['gather', 'connection'],
  ['gathering', 'connection'],
  ['hug', 'connection'],
  ['hugs', 'connection'],
  ['embrace', 'connection'],
  ['squeeze', 'connection'],
  ['touch', 'connection', 'body'],
  ['touching', 'connection', 'body'],
  ['shared', 'connection', 'abundance'],
  ['sharing', 'connection', 'abundance'],
  ['share', 'connection', 'abundance'],
  ['giving', 'connection', 'abundance'],
  ['give', 'connection', 'abundance'],
  ['kindness', 'connection'],
  ['kind', 'connection'],
  ['affection', 'connection'],
  ['fondness', 'connection'],
  ['love', 'connection'],
  ['loving', 'connection'],
  ['beloved', 'connection'],
  ['seen', 'connection'],
  ['heard', 'connection'],
  ['understood', 'connection'],
  ['listen', 'connection'],
  ['listening', 'connection'],
  ['voice', 'connection', 'art'],
  ['welcoming', 'connection'],
  ['alongside', 'connection'],
  ['nearness', 'connection'],
  ['reunited', 'connection'],
  ['kinship', 'connection'],

  // ---------- wonder ----------
  ['wonder', 'wonder'],
  ['awe', 'wonder'],
  ['marvel', 'wonder'],
  ['splendor', 'wonder', 'light'],
  ['marvelous', 'wonder'],
  ['amazing', 'wonder'],
  ['mystery', 'wonder'],
  ['magic', 'wonder'],
  ['magical', 'wonder'],
  ['enchanted', 'wonder'],
  ['enchantment', 'wonder'],
  ['curious', 'wonder'],
  ['curiosity', 'wonder'],
  ['discovery', 'wonder'],
  ['discover', 'wonder'],
  ['explore', 'wonder'],
  ['exploring', 'wonder'],
  ['new', 'wonder', 'time'],
  ['newness', 'wonder'],
  ['fresh', 'wonder'],
  ['emerging', 'open', 'wonder'],
  ['emerge', 'open', 'wonder'],
  ['emergence', 'open', 'wonder'],
  ['creation', 'wonder', 'art'],
  ['creativity', 'art', 'open'],
  ['ever emerging', 'open', 'time'],
  ['always new', 'wonder', 'time'],
  ['always fresh', 'wonder', 'time'],
  ['just this', 'open', 'calm'],
  ['freshness', 'wonder'],
  ['renew', 'wonder'],
  ['renewal', 'wonder'],
  ['renewed', 'wonder'],
  ['beginning', 'wonder', 'time'],
  ['transformation', 'wonder'],
  ['becoming', 'wonder'],
  ['beauty', 'wonder', 'art'],
  ['beautiful', 'wonder', 'art'],
  ['elegance', 'wonder'],
  ['vivid', 'wonder', 'art'],
  ['vibrant', 'wonder', 'art'],
  ['spark', 'wonder', 'light'],
  ['glimpse', 'wonder'],
  ['twinkling', 'wonder', 'light'],
  ['imagination', 'wonder'],
  ['imaginative', 'wonder', 'play'],
  ['imagine', 'wonder'],
  ['dreaming', 'wonder'],
  ['wondrous', 'wonder'],
  ['astonishing', 'wonder'],

  // ---------- abundance ----------
  ['abundance', 'abundance'],
  ['abundant', 'abundance'],
  ['plenty', 'abundance'],
  ['plentiful', 'abundance'],
  ['bountiful', 'abundance'],
  ['harvest', 'abundance', 'nature'],
  ['overflow', 'abundance'],
  ['overflowing', 'abundance'],
  ['brimming', 'abundance'],
  ['full', 'abundance'],
  ['fullness', 'abundance'],
  ['rich', 'abundance'],
  ['richness', 'abundance'],
  ['lush', 'abundance', 'nature'],
  ['generous', 'abundance', 'connection'],
  ['generosity', 'abundance', 'connection'],
  ['gift', 'abundance'],
  ['gifts', 'abundance'],
  ['treasure', 'abundance'],
  ['flourish', 'abundance', 'nature'],
  ['flourishing', 'abundance', 'nature'],
  ['thriving', 'abundance', 'nature'],
  ['growing', 'abundance', 'nature'],
  ['grow', 'abundance', 'nature'],
  ['ripe', 'abundance', 'nature'],
  ['ripening', 'abundance', 'nature'],
  ['feast', 'abundance'],
  ['many', 'abundance'],
  ['deep', 'abundance', 'open'],

  // ---------- timelessness ----------
  ['now', 'time'],
  ['here', 'time'],
  ['this', 'time'],
  ['always', 'time'],
  ['forever', 'time'],
  ['eternal', 'time'],
  ['eternity', 'time'],
  ['timeless', 'time'],
  ['timelessness', 'time'],
  ['moment', 'time'],
  ['moments', 'time'],
  ['present', 'time'],
  ['lasting', 'time'],
  ['ongoing', 'time'],
  ['continuous', 'time'],
  ['cycle', 'time'],
  ['cycles', 'time'],
  ['season', 'time', 'nature'],
  ['seasons', 'time', 'nature'],
  ['rhythm', 'time', 'art'],
  ['tempo', 'time', 'art'],
  ['again', 'time'],
  ['return', 'time'],
  ['returning', 'time'],
  ['ancient', 'time', 'wonder'],
  ['perpetual', 'time'],
  ['perennial', 'time', 'nature'],

  // ---------- texture ----------
  ['soft', 'texture', 'calm'],
  ['softness', 'texture'],
  ['velvet', 'texture'],
  ['velvety', 'texture'],
  ['silk', 'texture'],
  ['silken', 'texture'],
  ['silky', 'texture'],
  ['satin', 'texture'],
  ['fleece', 'texture'],
  ['wool', 'texture'],
  ['woolly', 'texture'],
  ['cotton', 'texture'],
  ['linen', 'texture'],
  ['fuzzy', 'texture'],
  ['furry', 'texture'],
  ['fur', 'texture'],
  ['sleek', 'texture'],
  ['glossy', 'texture'],
  ['round', 'texture'],
  ['rounded', 'texture'],
  ['curve', 'texture'],
  ['curves', 'texture'],
  ['curved', 'texture'],
  ['cushion', 'texture', 'calm'],
  ['supple', 'texture'],
  ['gossamer', 'texture'],
  ['buttery', 'texture'],
  ['creamy', 'texture'],
  ['grainy', 'texture'],
  ['crinkle', 'texture'],
  ['ruffle', 'texture'],
  ['folds', 'texture'],
  ['nubby', 'texture'],
  ['brushed', 'texture'],
  ['featherlight', 'texture'],
  ['buoyancy', 'open', 'water'],
  ['airborne', 'texture', 'sky'],

  // ---------- color and music ----------
  ['art', 'art'],
  ['color', 'art'],
  ['colors', 'art'],
  ['colorful', 'art'],
  ['blue', 'art'],
  ['azure', 'art'],
  ['indigo', 'art'],
  ['cobalt', 'art'],
  ['teal', 'art'],
  ['turquoise', 'art'],
  ['aquamarine', 'art', 'water'],
  ['green', 'art'],
  ['emerald', 'art'],
  ['jade', 'art'],
  ['yellow', 'art'],
  ['copper', 'art'],
  ['bronze', 'art'],
  ['silver', 'art'],
  ['pearl', 'art'],
  ['cream', 'art'],
  ['coral', 'art', 'water'],
  ['pink', 'art'],
  ['red', 'art'],
  ['violet', 'art'],
  ['purple', 'art'],
  ['magenta', 'art'],
  ['hue', 'art'],
  ['hues', 'art'],
  ['tint', 'art'],
  ['palette', 'art'],
  ['spectrum', 'art'],
  ['paint', 'art'],
  ['painting', 'art'],
  ['brush', 'art'],
  ['canvas', 'art'],
  ['pottery', 'art'],
  ['sketch', 'art'],
  ['sketchbook', 'art'],
  ['watercolor', 'art'],
  ['finger paint', 'art', 'play'],
  ['journal', 'art'],
  ['drawing', 'art'],
  ['pattern', 'art'],
  ['patterns', 'art'],
  ['ink', 'art'],
  ['music', 'art'],
  ['musical', 'art'],
  ['melody', 'art'],
  ['melodies', 'art'],
  ['song', 'art'],
  ['songs', 'art'],
  ['sing', 'art'],
  ['singing', 'art'],
  ['tune', 'art'],
  ['note', 'art'],
  ['notes', 'art'],
  ['chord', 'art'],
  ['chords', 'art'],
  ['harmony', 'art', 'connection'],
  ['harmonies', 'art'],
  ['resonance', 'art'],
  ['resonant', 'art'],
  ['chime', 'art'],
  ['chimes', 'art'],
  ['bell', 'art'],
  ['bells', 'art'],
  ['drum', 'art'],
  ['drums', 'art'],
  ['flute', 'art'],
  ['violin', 'art'],
  ['cello', 'art'],
  ['piano', 'art'],
  ['guitar', 'art'],
  ['harp', 'art'],
  ['strings', 'art'],
  ['chorus', 'art', 'connection'],
  ['refrain', 'art'],
  ['echo', 'art'],
  ['sound', 'art'],
  ['tone', 'art'],
  ['hum', 'art', 'calm'],
  ['sonorous', 'art'],
  ['lilting', 'art'],
  ['cadence', 'art', 'time'],

  // added by hand after the first pass
  ['collaboration', 'connection', 'play'],
  ['unity', 'connection', 'open'],
  ['alchemy', 'wonder', 'art'],
  ['blessing', 'abundance', 'connection'],
  ['synchronicity', 'wonder', 'time'],
  ['ember', 'light', 'calm'],
  ['thunder', 'sky', 'nature'],
  ['youth', 'joy', 'time'],

  // ---- outer space -----------------------------------------------------
  // The furthest thing from the inside of a head. A handful of these are
  // proper names rather than plain nouns, which is the one place the list
  // breaks its own concrete-and-sensory rule: 'andromeda' means nothing to
  // the body, but it means somewhere very far away, and that is the job.
  ['cosmos', 'space', 'wonder'],
  ['cosmic', 'space', 'wonder'],
  ['universe', 'space', 'wonder'],
  ['galaxies', 'space', 'wonder'],
  ['quasar', 'space'],
  ['pulsar', 'space'],
  ['supernova', 'space', 'light'],
  ['starfield', 'space', 'light'],
  ['stardust', 'space', 'light'],
  ['interstellar', 'space'],
  ['celestial', 'space', 'wonder'],
  ['astral', 'space'],
  ['firmament', 'space', 'sky'],
  ['heavens', 'space', 'sky'],
  ['spacetime', 'space', 'time'],
  ['immensity', 'space', 'open'],
  ['infinity', 'space', 'time'],
  ['eternities', 'space', 'time'],
  ['lightyear', 'space', 'time'],
  ['filament', 'space', 'texture'],
  ['cluster', 'space'],
  ['halo', 'space', 'light'],
  ['corona', 'space', 'light'],
  ['magnetosphere', 'space'],
  ['ionosphere', 'space', 'sky'],
  ['gravity', 'space'],
  ['weightlessness', 'space', 'open'],
  ['orbiting', 'space', 'movement'],
  ['rotation', 'space', 'movement'],
  ['planets', 'space'],
  ['moons', 'space', 'sky'],
  ['comets', 'space', 'movement'],
  ['meteor', 'space', 'light'],
  ['meteorite', 'space'],
  ['crater', 'space', 'texture'],
  ['mercury', 'space'],
  ['venus', 'space'],
  ['mars', 'space'],
  ['jupiter', 'space'],
  ['saturn', 'space'],
  ['uranus', 'space'],
  ['neptune', 'space'],
  ['pluto', 'space'],
  ['telescope', 'space', 'wonder'],
  ['observatory', 'space'],
  ['satellite', 'space'],
  ['spacecraft', 'space'],
  ['rocket', 'space', 'play'],
  ['launch', 'space', 'movement'],
  ['astronaut', 'space'],
  ['spacewalk', 'space', 'movement'],
  ['capsule', 'space'],
  ['lander', 'space'],
  ['probe', 'space'],
  ['liftoff', 'space', 'movement'],
  ['countdown', 'space', 'time'],
  ['weightless', 'space', 'open'],
  ['freefall', 'space', 'movement'],
  ['solar', 'space', 'light'],
  ['lunar', 'space', 'sky'],
  ['eclipse', 'space', 'light'],
  ['sunspot', 'space', 'light'],
  ['flare', 'space', 'light'],
  ['speed of light', 'space', 'light'],
  // ---- more birds --------------------------------------------------------
  // Plain garden and shore birds only. No raptors and no national or party
  // symbols: a word that is a bird in a field guide can be something else
  // entirely on a flash card, which is how eagle, donkey and elephant got cut.
  ['chickadee', 'creatures'],
  ['nuthatch', 'creatures'],
  ['warbler', 'creatures'],
  ['thrush', 'creatures'],
  ['starling', 'creatures'],
  ['oriole', 'creatures'],
  ['bunting', 'creatures'],
  ['siskin', 'creatures'],
  ['linnet', 'creatures'],
  ['pipit', 'creatures'],
  ['jay', 'creatures'],
  ['swift', 'creatures'],
  ['martin', 'creatures'],
  ['quail', 'creatures'],
  ['dipper', 'creatures'],
  ['plover', 'creatures', 'water'],
  ['sandpiper', 'creatures', 'water'],
  ['egret', 'creatures', 'water'],
  ['tern', 'creatures', 'water'],
  ['puffin', 'creatures', 'water'],
  ['grebe', 'creatures', 'water'],
  ['moorhen', 'creatures', 'water'],
  ['curlew', 'creatures', 'water'],
  ['cygnet', 'creatures'],
  ['fledgling', 'creatures'],
  ['nestling', 'creatures'],
  ['hatchling', 'creatures'],
  ['plumage', 'creatures', 'texture'],
  ['perch', 'creatures'],
  ['roost', 'creatures', 'calm'],
  ['preen', 'creatures'],
  ['warble', 'creatures', 'art'],
  ['trill', 'creatures', 'art'],
  ['chirp', 'creatures', 'art'],
  ['chirping', 'creatures', 'art'],
  ['cooing', 'creatures', 'calm'],
  ['birdcall', 'creatures', 'art'],
  ['wingbeat', 'creatures', 'movement']
];
