//! Generated by tools/heart-protocol.mjs from heart/protocol.json. Do not edit:
//! change the JSON and run `node tools/heart-protocol.mjs`.

use crate::node::Rate;
use crate::protocol::Reader;

/// Command op codes.
pub mod op {
    pub const CREATE: u16 = 1;
    pub const DESTROY: u16 = 2;
    pub const CONNECT: u16 = 3;
    pub const CONNECT_PARAM: u16 = 4;
    pub const DISCONNECT_ALL: u16 = 5;
    pub const DISCONNECT_NODE: u16 = 6;
    pub const DISCONNECT_OUTPUT: u16 = 7;
    pub const DISCONNECT_PARAM: u16 = 8;
    pub const PARAM_SET: u16 = 10;
    pub const PARAM_LINEAR: u16 = 11;
    pub const PARAM_EXP: u16 = 12;
    pub const PARAM_TARGET: u16 = 13;
    pub const PARAM_CURVE: u16 = 14;
    pub const PARAM_CANCEL: u16 = 15;
    pub const PARAM_CANCEL_HOLD: u16 = 16;
    pub const ATTR: u16 = 20;
    pub const CHANNELS: u16 = 21;
    pub const START: u16 = 22;
    pub const STOP: u16 = 23;
    pub const MESSAGE: u16 = 24;
    pub const PEAK_REQUEST: u16 = 25;
}

/// Event op codes.
pub mod event {
    pub const ENDED: u16 = 101;
    pub const PEAK: u16 = 102;
    pub const PORT: u16 = 103;
    pub const STATS: u16 = 104;
    pub const LOG: u16 = 105;
}

/// Node kinds, as node.rs numbers them (checked when this file is made).
pub mod kind {
    pub const GAIN: u32 = 1;
    pub const CONSTANT_SOURCE: u32 = 2;
    pub const STEREO_PANNER: u32 = 3;
    pub const DELAY: u32 = 4;
    pub const BIQUAD: u32 = 5;
    pub const OSCILLATOR: u32 = 6;
    pub const BUFFER_SOURCE: u32 = 7;
    pub const ANALYSER: u32 = 8;
    pub const CONVOLVER: u32 = 9;
    pub const FDN: u32 = 10;
    pub const ONE_POLE: u32 = 11;
    pub const STROBE_SIGNAL: u32 = 12;
    pub const GENUS: u32 = 13;
    pub const EGRESS: u32 = 14;
    pub const INGRESS: u32 = 15;
    pub const MASTER: u32 = 16;
}

/// Attribute ids for the attr command.
pub mod attr {
    pub const TYPE: u32 = 1;
    pub const LOOP: u32 = 2;
    pub const LOOP_START: u32 = 3;
    pub const LOOP_END: u32 = 4;
    pub const BUFFER: u32 = 5;
    pub const NORMALIZE: u32 = 6;
    pub const FFT_SIZE: u32 = 7;
}

/// The biquad_type enum's values on the wire.
pub mod biquad_type {
    pub const LOWPASS: u32 = 0;
    pub const HIGHPASS: u32 = 1;
    pub const BANDPASS: u32 = 2;
    pub const LOWSHELF: u32 = 3;
    pub const HIGHSHELF: u32 = 4;
    pub const PEAKING: u32 = 5;
    pub const NOTCH: u32 = 6;
    pub const ALLPASS: u32 = 7;
}

/// The oscillator_type enum's values on the wire.
pub mod oscillator_type {
    pub const SINE: u32 = 0;
    pub const SQUARE: u32 = 1;
    pub const SAWTOOTH: u32 = 2;
    pub const TRIANGLE: u32 = 3;
}

/// The channel_count_mode enum's values on the wire.
pub mod channel_count_mode {
    pub const MAX: u32 = 0;
    pub const CLAMPED_MAX: u32 = 1;
    pub const EXPLICIT: u32 = 2;
}

/// The channel_interpretation enum's values on the wire.
pub mod channel_interpretation {
    pub const SPEAKERS: u32 = 0;
    pub const DISCRETE: u32 = 1;
}

/// The log_code enum's values on the wire.
pub mod log_code {
    pub const CYCLE_CUT: u32 = 1;
}

/// Message types of strobe_signal_in (processor_messages).
pub mod strobe_signal_in {
    pub const SIGNAL: u32 = 1;
}

/// Message types of genus_in (processor_messages).
pub mod genus_in {
    pub const SIGNAL: u32 = 1;
    pub const METERS: u32 = 2;
    pub const DIP_WATCH: u32 = 3;
    pub const CHIRP: u32 = 4;
}

/// Message types of genus_out (processor_messages).
pub mod genus_out {
    pub const PEAKS: u32 = 101;
    pub const DIP: u32 = 102;
    pub const CHIRP_ACK: u32 = 103;
}

/// A param bound as the protocol gives it: a number, or one that depends on
/// the context (Nyquist(k) is k times half the sample rate) or on the node
/// (the delay's maxDelayTime, create's first option).
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Bound { Value(f32), Nyquist(f32), MaxDelayTime }

#[derive(Clone, Copy, Debug)]
pub struct ParamRow { pub name: &'static str, pub default: f32, pub min: Bound, pub max: Bound, pub rate: Rate }

static GAIN_PARAMS: [ParamRow; 1] = [
    ParamRow { name: "gain", default: 1.0, min: Bound::Value(-f32::MAX), max: Bound::Value(f32::MAX), rate: Rate::A },
];
static CONSTANT_SOURCE_PARAMS: [ParamRow; 1] = [
    ParamRow { name: "offset", default: 1.0, min: Bound::Value(-f32::MAX), max: Bound::Value(f32::MAX), rate: Rate::A },
];
static STEREO_PANNER_PARAMS: [ParamRow; 1] = [
    ParamRow { name: "pan", default: 0.0, min: Bound::Value(-1.0), max: Bound::Value(1.0), rate: Rate::A },
];
static DELAY_PARAMS: [ParamRow; 1] = [
    ParamRow { name: "delayTime", default: 0.0, min: Bound::Value(0.0), max: Bound::MaxDelayTime, rate: Rate::A },
];
static BIQUAD_PARAMS: [ParamRow; 4] = [
    ParamRow { name: "frequency", default: 350.0, min: Bound::Value(0.0), max: Bound::Nyquist(1.0), rate: Rate::A },
    ParamRow { name: "detune", default: 0.0, min: Bound::Value(-153600.0), max: Bound::Value(153600.0), rate: Rate::A },
    ParamRow { name: "Q", default: 1.0, min: Bound::Value(-f32::MAX), max: Bound::Value(f32::MAX), rate: Rate::A },
    ParamRow { name: "gain", default: 0.0, min: Bound::Value(-1541.0), max: Bound::Value(1541.0), rate: Rate::A },
];
static OSCILLATOR_PARAMS: [ParamRow; 2] = [
    ParamRow { name: "frequency", default: 440.0, min: Bound::Nyquist(-1.0), max: Bound::Nyquist(1.0), rate: Rate::A },
    ParamRow { name: "detune", default: 0.0, min: Bound::Value(-153600.0), max: Bound::Value(153600.0), rate: Rate::A },
];
static BUFFER_SOURCE_PARAMS: [ParamRow; 2] = [
    ParamRow { name: "playbackRate", default: 1.0, min: Bound::Value(-f32::MAX), max: Bound::Value(f32::MAX), rate: Rate::K },
    ParamRow { name: "detune", default: 0.0, min: Bound::Value(-f32::MAX), max: Bound::Value(f32::MAX), rate: Rate::K },
];
static ANALYSER_PARAMS: [ParamRow; 0] = [
];
static CONVOLVER_PARAMS: [ParamRow; 0] = [
];
static FDN_PARAMS: [ParamRow; 3] = [
    ParamRow { name: "decay", default: 4.5, min: Bound::Value(0.1), max: Bound::Value(60.0), rate: Rate::K },
    ParamRow { name: "damping", default: 0.35, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
    ParamRow { name: "mod", default: 0.3, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
];
static ONE_POLE_PARAMS: [ParamRow; 1] = [
    ParamRow { name: "frequency", default: 24000.0, min: Bound::Value(0.0), max: Bound::Value(96000.0), rate: Rate::A },
];
static STROBE_SIGNAL_PARAMS: [ParamRow; 0] = [
];
static GENUS_PARAMS: [ParamRow; 27] = [
    ParamRow { name: "rate", default: 40.0, min: Bound::Value(0.05), max: Bound::Value(200.0), rate: Rate::K },
    ParamRow { name: "amDepth", default: 1.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::A },
    ParamRow { name: "carrier", default: 200.0, min: Bound::Value(20.0), max: Bound::Value(20000.0), rate: Rate::K },
    ParamRow { name: "pipMs", default: 5.0, min: Bound::Value(0.1), max: Bound::Value(100.0), rate: Rate::K },
    ParamRow { name: "toneLevel", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::A },
    ParamRow { name: "clickLevel", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::A },
    ParamRow { name: "clickSend", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::A },
    ParamRow { name: "chirpLevel", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::A },
    ParamRow { name: "chirpSend", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::A },
    ParamRow { name: "clickModDepth", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
    ParamRow { name: "clickModRate", default: 0.1, min: Bound::Value(0.005), max: Bound::Value(8.0), rate: Rate::K },
    ParamRow { name: "biDepth", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
    ParamRow { name: "biRate", default: 1.0, min: Bound::Value(0.02), max: Bound::Value(4.0), rate: Rate::K },
    ParamRow { name: "biHard", default: 1.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
    ParamRow { name: "harmLevel", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::A },
    ParamRow { name: "harmCount", default: 6.0, min: Bound::Value(1.0), max: Bound::Value(16.0), rate: Rate::K },
    ParamRow { name: "harmBright", default: 1.2, min: Bound::Value(0.1), max: Bound::Value(4.0), rate: Rate::K },
    ParamRow { name: "harmSpread", default: 0.7, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
    ParamRow { name: "harmPanRate", default: 0.15, min: Bound::Value(0.0), max: Bound::Value(4.0), rate: Rate::K },
    ParamRow { name: "shimDepth", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
    ParamRow { name: "shimRate", default: 0.25, min: Bound::Value(0.01), max: Bound::Value(6.0), rate: Rate::K },
    ParamRow { name: "lpfOn", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
    ParamRow { name: "lpfLo", default: 400.0, min: Bound::Value(20.0), max: Bound::Value(20000.0), rate: Rate::K },
    ParamRow { name: "lpfHi", default: 9000.0, min: Bound::Value(20.0), max: Bound::Value(20000.0), rate: Rate::K },
    ParamRow { name: "lpfPeriod", default: 60.0, min: Bound::Value(0.5), max: Bound::Value(600.0), rate: Rate::K },
    ParamRow { name: "lpfQ", default: 0.707, min: Bound::Value(0.3), max: Bound::Value(10.0), rate: Rate::K },
    ParamRow { name: "lpfWander", default: 0.0, min: Bound::Value(0.0), max: Bound::Value(1.0), rate: Rate::K },
];
static EGRESS_PARAMS: [ParamRow; 0] = [
];
static INGRESS_PARAMS: [ParamRow; 0] = [
];
static MASTER_PARAMS: [ParamRow; 0] = [
];

/// A kind's params in wire order (a param id is its index here).
pub fn params(kind: u32) -> &'static [ParamRow] {
    match kind {
        1 => &GAIN_PARAMS,
        2 => &CONSTANT_SOURCE_PARAMS,
        3 => &STEREO_PANNER_PARAMS,
        4 => &DELAY_PARAMS,
        5 => &BIQUAD_PARAMS,
        6 => &OSCILLATOR_PARAMS,
        7 => &BUFFER_SOURCE_PARAMS,
        8 => &ANALYSER_PARAMS,
        9 => &CONVOLVER_PARAMS,
        10 => &FDN_PARAMS,
        11 => &ONE_POLE_PARAMS,
        12 => &STROBE_SIGNAL_PARAMS,
        13 => &GENUS_PARAMS,
        14 => &EGRESS_PARAMS,
        15 => &INGRESS_PARAMS,
        16 => &MASTER_PARAMS,
        _ => &[],
    }
}

/// One command, its fields decoded (the node id is in the record head).
#[derive(Clone, Debug, PartialEq)]
pub enum Command<'a> {
    Create { kind: u32, island: u32, opts: [f64; 8] },
    Destroy,
    Connect { output: u32, target: u32, input: u32 },
    ConnectParam { output: u32, target: u32, param: u32 },
    DisconnectAll,
    DisconnectNode { target: u32 },
    DisconnectOutput { output: u32 },
    DisconnectParam { target: u32, param: u32 },
    ParamSet { param: u32, time: f64, value: f32 },
    ParamLinear { param: u32, time: f64, value: f32 },
    ParamExp { param: u32, time: f64, value: f32 },
    ParamTarget { param: u32, time: f64, value: f32, tau: f64 },
    ParamCurve { param: u32, time: f64, duration: f64, values: Vec<f32> },
    ParamCancel { param: u32, time: f64 },
    ParamCancelHold { param: u32, time: f64 },
    Attr { attr: u32, value: f64 },
    Channels { count: u32, mode: u32, interpretation: u32 },
    Start { time: f64, offset: f64, duration: f64 },
    Stop { time: f64 },
    Message { bytes: &'a [u8] },
    PeakRequest,
}

/// Decodes a command's fields, the bytes after its record head. None for an
/// unknown op or fields cut short.
pub fn decode(op: u16, fields: &[u8]) -> Option<Command<'_>> {
    let mut r = Reader::new(fields);
    Some(match op {
        op::CREATE => Command::Create { kind: r.u32()?, island: r.u32()?, opts: r.f64x8()? },
        op::DESTROY => Command::Destroy,
        op::CONNECT => Command::Connect { output: r.u32()?, target: r.u32()?, input: r.u32()? },
        op::CONNECT_PARAM => Command::ConnectParam { output: r.u32()?, target: r.u32()?, param: r.u32()? },
        op::DISCONNECT_ALL => Command::DisconnectAll,
        op::DISCONNECT_NODE => Command::DisconnectNode { target: r.u32()? },
        op::DISCONNECT_OUTPUT => Command::DisconnectOutput { output: r.u32()? },
        op::DISCONNECT_PARAM => Command::DisconnectParam { target: r.u32()?, param: r.u32()? },
        op::PARAM_SET => Command::ParamSet { param: r.u32()?, time: r.f64()?, value: r.f32()? },
        op::PARAM_LINEAR => Command::ParamLinear { param: r.u32()?, time: r.f64()?, value: r.f32()? },
        op::PARAM_EXP => Command::ParamExp { param: r.u32()?, time: r.f64()?, value: r.f32()? },
        op::PARAM_TARGET => Command::ParamTarget { param: r.u32()?, time: r.f64()?, value: r.f32()?, tau: r.f64()? },
        op::PARAM_CURVE => Command::ParamCurve { param: r.u32()?, time: r.f64()?, duration: r.f64()?, values: r.f32s()? },
        op::PARAM_CANCEL => Command::ParamCancel { param: r.u32()?, time: r.f64()? },
        op::PARAM_CANCEL_HOLD => Command::ParamCancelHold { param: r.u32()?, time: r.f64()? },
        op::ATTR => Command::Attr { attr: r.u32()?, value: r.f64()? },
        op::CHANNELS => Command::Channels { count: r.u32()?, mode: r.u32()?, interpretation: r.u32()? },
        op::START => Command::Start { time: r.f64()?, offset: r.f64()?, duration: r.f64()? },
        op::STOP => Command::Stop { time: r.f64()? },
        op::MESSAGE => Command::Message { bytes: r.bytes()? },
        op::PEAK_REQUEST => Command::PeakRequest,
        _ => return None,
    })
}
