// Generated by tools/heart-protocol.mjs from heart/protocol.json. Do not edit:
// change the JSON and run `node tools/heart-protocol.mjs`.
//
// Records are little-endian: u16 op, u16 byteLength (the whole record), u32
// node, then the fields. Times are engine frames (f64), except a target's
// tau and a curve's duration, which are seconds.

// Node kinds by name.
export const KINDS = Object.freeze({
  gain: 1,
  constant_source: 2,
  stereo_panner: 3,
  delay: 4,
  biquad: 5,
  oscillator: 6,
  buffer_source: 7,
  analyser: 8,
  convolver: 9,
  fdn: 10,
  one_pole: 11,
  strobe_signal: 12,
  genus: 13,
  egress: 14,
  ingress: 15,
  master: 16
});

// Attribute ids for Commands.attr.
export const ATTRS = Object.freeze({
  type: 1,
  loop: 2,
  loopStart: 3,
  loopEnd: 4,
  buffer: 5,
  normalize: 6,
  fftSize: 7
});

// Enum values on the wire, by enum and name.
export const ENUMS = Object.freeze({
  biquad_type: Object.freeze({
    lowpass: 0,
    highpass: 1,
    bandpass: 2,
    lowshelf: 3,
    highshelf: 4,
    peaking: 5,
    notch: 6,
    allpass: 7
  }),
  oscillator_type: Object.freeze({
    sine: 0,
    square: 1,
    sawtooth: 2,
    triangle: 3
  }),
  channel_count_mode: Object.freeze({
    max: 0,
    "clamped-max": 1,
    explicit: 2
  }),
  channel_interpretation: Object.freeze({
    speakers: 0,
    discrete: 1
  }),
  log_code: Object.freeze({
    cycle_cut: 1
  })
});

// Each kind's params in wire order, as [name, default, min, max, rate]. A bound is a
// number or a name: 'max' (f32's largest, '-max' its negative), 'nyquist' (half the
// sample rate, '-nyquist'), 'maxDelayTime' (the delay's create option).
export const PARAMS = Object.freeze({
  gain: Object.freeze([
    Object.freeze(["gain", 1, "-max", "max", "a"])
  ]),
  constant_source: Object.freeze([
    Object.freeze(["offset", 1, "-max", "max", "a"])
  ]),
  stereo_panner: Object.freeze([
    Object.freeze(["pan", 0, -1, 1, "a"])
  ]),
  delay: Object.freeze([
    Object.freeze(["delayTime", 0, 0, "maxDelayTime", "a"])
  ]),
  biquad: Object.freeze([
    Object.freeze(["frequency", 350, 0, "nyquist", "a"]),
    Object.freeze(["detune", 0, -153600, 153600, "a"]),
    Object.freeze(["Q", 1, "-max", "max", "a"]),
    Object.freeze(["gain", 0, -1541, 1541, "a"])
  ]),
  oscillator: Object.freeze([
    Object.freeze(["frequency", 440, "-nyquist", "nyquist", "a"]),
    Object.freeze(["detune", 0, -153600, 153600, "a"])
  ]),
  buffer_source: Object.freeze([
    Object.freeze(["playbackRate", 1, "-max", "max", "k"]),
    Object.freeze(["detune", 0, "-max", "max", "k"])
  ]),
  analyser: Object.freeze([]),
  convolver: Object.freeze([]),
  fdn: Object.freeze([
    Object.freeze(["decay", 4.5, 0.1, 60, "k"]),
    Object.freeze(["damping", 0.35, 0, 1, "k"]),
    Object.freeze(["mod", 0.3, 0, 1, "k"])
  ]),
  one_pole: Object.freeze([
    Object.freeze(["frequency", 24000, 0, 96000, "a"])
  ]),
  strobe_signal: Object.freeze([]),
  genus: Object.freeze([
    Object.freeze(["rate", 40, 0.05, 200, "k"]),
    Object.freeze(["amDepth", 1, 0, 1, "a"]),
    Object.freeze(["carrier", 200, 20, 20000, "k"]),
    Object.freeze(["pipMs", 5, 0.1, 100, "k"]),
    Object.freeze(["toneLevel", 0, 0, 1, "a"]),
    Object.freeze(["clickLevel", 0, 0, 1, "a"]),
    Object.freeze(["clickSend", 0, 0, 1, "a"]),
    Object.freeze(["chirpLevel", 0, 0, 1, "a"]),
    Object.freeze(["chirpSend", 0, 0, 1, "a"]),
    Object.freeze(["clickModDepth", 0, 0, 1, "k"]),
    Object.freeze(["clickModRate", 0.1, 0.005, 8, "k"]),
    Object.freeze(["biDepth", 0, 0, 1, "k"]),
    Object.freeze(["biRate", 1, 0.02, 4, "k"]),
    Object.freeze(["biHard", 1, 0, 1, "k"]),
    Object.freeze(["harmLevel", 0, 0, 1, "a"]),
    Object.freeze(["harmCount", 6, 1, 16, "k"]),
    Object.freeze(["harmBright", 1.2, 0.1, 4, "k"]),
    Object.freeze(["harmSpread", 0.7, 0, 1, "k"]),
    Object.freeze(["harmPanRate", 0.15, 0, 4, "k"]),
    Object.freeze(["shimDepth", 0, 0, 1, "k"]),
    Object.freeze(["shimRate", 0.25, 0.01, 6, "k"]),
    Object.freeze(["lpfOn", 0, 0, 1, "k"]),
    Object.freeze(["lpfLo", 400, 20, 20000, "k"]),
    Object.freeze(["lpfHi", 9000, 20, 20000, "k"]),
    Object.freeze(["lpfPeriod", 60, 0.5, 600, "k"]),
    Object.freeze(["lpfQ", 0.707, 0.3, 10, "k"]),
    Object.freeze(["lpfWander", 0, 0, 1, "k"])
  ]),
  egress: Object.freeze([]),
  ingress: Object.freeze([]),
  master: Object.freeze([])
});

// Command op codes.
export const OPS = Object.freeze({
  create: 1,
  destroy: 2,
  connect: 3,
  connect_param: 4,
  disconnect_all: 5,
  disconnect_node: 6,
  disconnect_output: 7,
  disconnect_param: 8,
  param_set: 10,
  param_linear: 11,
  param_exp: 12,
  param_target: 13,
  param_curve: 14,
  param_cancel: 15,
  param_cancel_hold: 16,
  attr: 20,
  channels: 21,
  start: 22,
  stop: 23,
  message: 24,
  peak_request: 25
});

// Event op codes.
export const EVENT_OPS = Object.freeze({
  ended: 101,
  peak: 102,
  port: 103,
  stats: 104,
  log: 105
});

// Processor message types (a message's leading u32), by direction and name.
export const MESSAGES = Object.freeze({
  strobe_signal_in: Object.freeze({
    signal: 1
  }),
  genus_in: Object.freeze({
    signal: 1,
    meters: 2,
    dipWatch: 3,
    chirp: 4
  }),
  genus_out: Object.freeze({
    peaks: 101,
    dip: 102,
    chirpAck: 103
  })
});

// A batch of command records, one method per command (arguments: the node,
// then the fields in protocol order). bytes() is a view of what has been
// written, valid until the next write or reset(); copy it (slice) to keep it
// or to transfer it.
export class Commands {
  constructor(capacity = 1024) {
    this._at = 0;
    this._take(new ArrayBuffer(capacity));
  }
  get length() { return this._at; }
  bytes() { return this._u8.subarray(0, this._at); }
  reset() { this._at = 0; }

  _take(buf) {
    this._buf = buf;
    this._dv = new DataView(buf);
    this._u8 = new Uint8Array(buf);
  }
  // Starts a record of `len` bytes and returns where its fields go.
  _open(op, len, node) {
    if (len > 65535) throw new RangeError(`Heart: a ${len}-byte record is longer than the protocol's 65535`);
    const end = this._at + len;
    if (end > this._buf.byteLength) {
      let cap = this._buf.byteLength * 2;
      while (cap < end) cap *= 2;
      const old = this._u8.subarray(0, this._at);
      this._take(new ArrayBuffer(cap));
      this._u8.set(old);
    }
    const at = this._at, dv = this._dv;
    dv.setUint16(at, op, true);
    dv.setUint16(at + 2, len, true);
    dv.setUint32(at + 4, node >>> 0, true);
    this._at = end;
    return at + 8;
  }
  // An array field: its u32 count, the items, zeros to the next 4 bytes.
  _f32s(at, values) {
    const n = values.length, dv = this._dv;
    dv.setUint32(at, n, true);
    for (let i = 0; i < n; i++) dv.setFloat32(at + 4 + 4 * i, values[i], true);
  }
  _bytes(at, bytes) {
    const n = bytes.length;
    this._dv.setUint32(at, n, true);
    this._u8.set(bytes, at + 4);
    this._u8.fill(0, at + 4 + n, at + 4 + n + pad(n));
  }

  create(node, kind, island, opts) {
    const at = this._open(1, 80, node), dv = this._dv;
    dv.setUint32(at, kind >>> 0, true);
    dv.setUint32(at + 4, island >>> 0, true);
    for (let i = 0; i < 8; i++) dv.setFloat64(at + 8 + 8 * i, +((opts && opts[i]) || 0), true);
  }

  destroy(node) {
    this._open(2, 8, node);
  }

  connect(node, output, target, input) {
    const at = this._open(3, 20, node), dv = this._dv;
    dv.setUint32(at, output >>> 0, true);
    dv.setUint32(at + 4, target >>> 0, true);
    dv.setUint32(at + 8, input >>> 0, true);
  }

  connectParam(node, output, target, param) {
    const at = this._open(4, 20, node), dv = this._dv;
    dv.setUint32(at, output >>> 0, true);
    dv.setUint32(at + 4, target >>> 0, true);
    dv.setUint32(at + 8, param >>> 0, true);
  }

  disconnectAll(node) {
    this._open(5, 8, node);
  }

  disconnectNode(node, target) {
    const at = this._open(6, 12, node), dv = this._dv;
    dv.setUint32(at, target >>> 0, true);
  }

  disconnectOutput(node, output) {
    const at = this._open(7, 12, node), dv = this._dv;
    dv.setUint32(at, output >>> 0, true);
  }

  disconnectParam(node, target, param) {
    const at = this._open(8, 16, node), dv = this._dv;
    dv.setUint32(at, target >>> 0, true);
    dv.setUint32(at + 4, param >>> 0, true);
  }

  paramSet(node, param, timeFrame, value) {
    const at = this._open(10, 24, node), dv = this._dv;
    dv.setUint32(at, param >>> 0, true);
    dv.setFloat64(at + 4, timeFrame, true);
    dv.setFloat32(at + 12, value, true);
  }

  paramLinear(node, param, timeFrame, value) {
    const at = this._open(11, 24, node), dv = this._dv;
    dv.setUint32(at, param >>> 0, true);
    dv.setFloat64(at + 4, timeFrame, true);
    dv.setFloat32(at + 12, value, true);
  }

  paramExp(node, param, timeFrame, value) {
    const at = this._open(12, 24, node), dv = this._dv;
    dv.setUint32(at, param >>> 0, true);
    dv.setFloat64(at + 4, timeFrame, true);
    dv.setFloat32(at + 12, value, true);
  }

  paramTarget(node, param, timeFrame, value, tauSec) {
    const at = this._open(13, 32, node), dv = this._dv;
    dv.setUint32(at, param >>> 0, true);
    dv.setFloat64(at + 4, timeFrame, true);
    dv.setFloat32(at + 12, value, true);
    dv.setFloat64(at + 16, tauSec, true);
  }

  paramCurve(node, param, timeFrame, durationSec, values) {
    const at = this._open(14, 32 + 4 * values.length, node), dv = this._dv;
    dv.setUint32(at, param >>> 0, true);
    dv.setFloat64(at + 4, timeFrame, true);
    dv.setFloat64(at + 12, durationSec, true);
    this._f32s(at + 20, values);
  }

  paramCancel(node, param, timeFrame) {
    const at = this._open(15, 20, node), dv = this._dv;
    dv.setUint32(at, param >>> 0, true);
    dv.setFloat64(at + 4, timeFrame, true);
  }

  paramCancelHold(node, param, timeFrame) {
    const at = this._open(16, 20, node), dv = this._dv;
    dv.setUint32(at, param >>> 0, true);
    dv.setFloat64(at + 4, timeFrame, true);
  }

  attr(node, attr, value) {
    const at = this._open(20, 20, node), dv = this._dv;
    dv.setUint32(at, attr >>> 0, true);
    dv.setFloat64(at + 4, value, true);
  }

  channels(node, count, mode, interpretation) {
    const at = this._open(21, 20, node), dv = this._dv;
    dv.setUint32(at, count >>> 0, true);
    dv.setUint32(at + 4, mode >>> 0, true);
    dv.setUint32(at + 8, interpretation >>> 0, true);
  }

  start(node, timeFrame, offset, durationSec) {
    const at = this._open(22, 32, node), dv = this._dv;
    dv.setFloat64(at, timeFrame, true);
    dv.setFloat64(at + 8, offset, true);
    dv.setFloat64(at + 16, durationSec, true);
  }

  stop(node, timeFrame) {
    const at = this._open(23, 16, node), dv = this._dv;
    dv.setFloat64(at, timeFrame, true);
  }

  message(node, bytes) {
    const at = this._open(24, 12 + bytes.length + pad(bytes.length), node);
    this._bytes(at, bytes);
  }

  peakRequest(node) {
    this._open(25, 8, node);
  }
}

function pad(n) { return (4 - n % 4) % 4; }

// Walks a batch of event records, calling fn(op, node, dataView, fieldOffset,
// recordEnd) for each; fieldOffset and recordEnd are byte offsets into the
// dataView, which spans exactly `u8`. Stops at a record that does not fit.
export function forEachEvent(u8, fn) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  for (let at = 0; at + 8 <= u8.byteLength;) {
    const op = dv.getUint16(at, true), len = dv.getUint16(at + 2, true);
    if (len < 8 || at + len > u8.byteLength) return;
    fn(op, dv.getUint32(at + 4, true), dv, at + 8, at + len);
    at += len;
  }
}
